### ISSUE TITLE
The dialog not insert first position when I set $.pnotify.defaults.history = false

### ISSUE THREAD

**Issue by aimilin6688** [sciactive/pnotify#109]
The dialog can't insert first row，when I set $.pnotify.defaults.history = false .

**Comment by nring** [comment]
Seeing this too

**Comment by nring** [comment]
I've been debugging this for hours but cannot find the cause. What I have been able to find:
* I can only reproduce it on the default stack, or when the push variable is "bottom".
* I've been able to reproduce based on standard JS and CSS. The only difference is that I reduced the delay for when the notification disappears: http://jsbin.com/howoxojuya/1/ (Click on the link, wait til the first notification disappears, then click on the link again. The second notification will appear as if the first notification is still present.)
* It looks like the bug might be occurring in the positionAll() function where nextpos1 is supposed to be set to firstpos1

I'll keep investigating and let you know if I find anything

**Comment by nring** [comment]
Not sure how I missed it, but It was an issue of me missing out on the new stacking order. I specified the following stack for it to work:

var stack_topright = {"dir1": "down", "dir2": "left", "push": "top", "firstpos1": 25, "firstpos2": 25};

See updated JSBin: http://jsbin.com/haduvalofa/1/edit

**Comment by KarelCemus** [comment]
I confirm the bug still exists in 2.0.1

**Comment by hperrin** [comment]
I'm not seeing this on your jsbin: (updated)
http://jsbin.com/xebalepume/edit?output

**Comment by hperrin** [comment]
Unable to reproduce.

**Comment by hperrin** [comment]
Just to be clear, this is the code I tested with:
http://jsbin.com/xaquxaneru/edit?output
