### ISSUE TITLE
Update Documentation for making builds

### ISSUE THREAD

**Issue by lord-xeon** [sciactive/pnotify#121]
When you clone the repository, or download the ZIP from GitHub, 
- pnotify.custom.js & pnotify.custom.min.js
- pnotify.custom.css & pnotify.custom.min.css

Are not included, and it's hard to just get going.

The build process (with buildcustom.php) has no documentation, and only by looking at the output files was I able to figure out what I needed to pass in to get it to generate a built file for me.

I think there should either be a built folder contained in the source, or an instruction file to explain how to build it.

**Comment by hperrin** [comment]
Fixed in develop branch. (v4)
