### ISSUE TITLE
Make desktop icons local

### ISSUE THREAD

**Issue by lord-xeon** [sciactive/pnotify#122]
The current default URL for the icons on the desktop plugin are hard-coded to http://sciactive.com/pnotify/

This should probably change to the local system

**Comment by hozza** [comment]
Deffo needs this... if you implement a Content Security Policy (CSP) for new web apps, which is recommended, it throws an error as it's trying to load content from your 'untrusted' (in the eyes of the CSP) CDN. 

Need's a parameter to specify own image, or if the 'icon' parameter is already set and is a URI - use that.
