### ISSUE TITLE
Composite download from sciactive.github.io/pnotify doesn't work. ReferenceError: PNotify is not defined 

### ISSUE THREAD

**Issue by Unislash** [sciactive/pnotify#125]
When downloading from sciactive.github.io/pnotify I am given a composite file with the different modules of pnotify all appended into one file. Sweet! Unfortunately, it seems that the mechanism for appending the extension modules to the core module doesn't include the cool new AMD support that was added a month ago.

When I try to use pnotify via requirejs, I am greeted with "ReferenceError: PNotify is not defined" on line 762.

I've only recently incorporated requirejs into my application, but from what I can see, the extension modules fire before the core module because they aren't actually an AMD module at all. If I split out the extension modules into a new module and define it as dependent on the core module, everything works. I'm not sure if this bug affects non-AMD users.

If you need any more details, just ask :-)

**Comment by grofit** [comment]
I get same issue in a electorn app which is using require and it blows up
