### ISSUE TITLE
doesn't work with require.js

### ISSUE THREAD

**Issue by maxwowpow** [sciactive/pnotify#130]
Hello,

I've tested pnotify 2.0.1 with Require JS, they don't work together well. #125
It seems like only the core is being loaded.

I've built a test case for this issue.
http://www.maxgrass.eu/pages/pnotify/

pnotify.custom has all modules, but buttons are not initialized.

It is usable, if one references all modules separately, but that's a bad habit: no minification, no optimization.

There should be a possibility to reference a single file, which is correctly compressed with all required modules.
This could be helpful: http://requirejs.org/docs/optimization.html

Regards, 
Max

**Comment by rvnath** [comment]
I face the same problem.  It doesn't show buttons when used with requirejs.  I could not get it to work, even when using unoptimized version.  How did you do it? Can you paste a working code sample?
