### ISSUE TITLE
Make it easier to use PNotify out of the box, when adding to existing, custom themed apps

### ISSUE THREAD

**Issue by jamesmortensen** [sciactive/pnotify#148]
Basically, to use PNotify with Bootstrap, it seems your entire app has to use Bootstrap, or you can't use PNotify.  

I've been selectively brining in some styles from the bootstrap.css file to get the notifications to style correctly.  If I bring in the entire bootstrap.css file, it conflicts with the work our designers already did in the app.  

The form example so far has been the worst. The button styles seem to be conflicting with something else. I'm doing my best to match up all of the styles so it looks like what's on the PNotify demo page.

My point here isn't to complain needlessly, but to demonstrate that this is a challenge that, if overcome, may increase user on-boarding.  This is a great library, but you have to drink all of the Bootstrap kool-aid in order to use it.  Whereas, I prefer to sip my Bootstrap kool-aid. :)  I haven't tried with jQuery UI or the other library, but I'm assuming it's the same or similar issue.

Is it possible to bundle up only the styles needed from these third party libraries so that one can make use of PNotify, standalone, without it affecting other parts of the app?

**Comment by grofit** [comment]
Just want to mention that I do not like bootstrap and I do not want jquery ui but I love pnotify, it would be great if there was a basic style which you could use as a template for making your own styles if you dont want to have to depend upon bootstrap or jquery ui

**Comment by hperrin** [comment]
@grofit That's what the latest commit added. It's called Bright Theme. I just pushed it to the development site (http://sciactive.github.io/pnotify/) so you can check it out. Select it under the "Choose the Styling" section.

**Comment by amurrell** [comment]
That's cool @hperrin :)
