### ISSUE TITLE
Bug in for-loop in pnotify.confirm.js / function makeDialog

### ISSUE THREAD

**Issue by omisch** [sciactive/pnotify#155]
Hi,

I believe I have found a bug in the function makeDialog in pnotify.confirm.js (version 2.0.1)

In this function, there is the following loop statement:

for (var i in options.buttons) {
    btn = options.buttons[i];
    ....
}

Somehow, in my case, the options.buttons array has a method 'move' as property (I don't know why, I do not add it). When iterating over all properties in options.buttons in the loop, one loop iteration has 'i' set to the 'move' function, resulting in an additional empty button rendered. 

If would be better if the loop only considers actual array elements of the array.

Best regards,
Oliver

**Comment by VeXHarbinger** [comment]
Was this ever resolved?  I'm getting that extra button in the latest version and also have a property called move as well.

**Comment by hperrin** [comment]
I believe this has been fixed, but not sure. I'm going to mark it as ready.

**Comment by hperrin** [comment]
This was fixed as part of another bug a while ago.
