### ISSUE TITLE
Initialize outside of page load

### ISSUE THREAD

**Issue by wallerjake** [sciactive/pnotify#159]
Is there a way to initialize PNotify outside of page load? I am specifically looking to load PNotify while using Turbo links. So it works fine if I am loading the page via a full load but it doesn't work when it loads through Turbo Links. The easiest fix to to add a hook into my Turbo Links code that can initialize PNotify uploading Turbo Links load. Is this possible? Otherwise I have to download and change core code.

I was thinking something like this.

<code>
PNotify.init();
</code>

Or:

<code>
$.pnotify();
</code>

**Comment by shemseddine** [comment]
Hellom, I'm just wondering.. are we able to reload the PNotify object yet? I'm came across this problem in my application and I'm running out of ideas

**Comment by hperrin** [comment]
It will be included in the next release.
