### ISSUE TITLE
error on addClass, pnotify.confirm.js

### ISSUE THREAD

**Issue by rudi911** [sciactive/pnotify#160]
When using the exact same code as on your demo part of the site I'm running into an issue with the prompt dialog. I'm using font awesome as styling, and the rest is default.
I've tried with the custom code when downloading from the site, as well as the individual modules from github. The exact error is:

Uncaught TypeError: Cannot read property 'addClass' of undefined 

on line 93 of pnotify.confirm.js.

All the default error and success type of notifications are running fine. I'm using 2.01

**Comment by codymullins** [comment]
This doesn't appear to be an issue. I cannot reproduce this using your code.
