### ISSUE TITLE
Multiple stacked bottom notifications not displayed correctly on page load

### ISSUE THREAD

**Issue by LDSign** [sciactive/pnotify#161]
Hi

Ive a weird problem, which I hope could be solved ;)

When displaying multiple notifications on page load (I call pnotify in loop function several times in document.ready) the messages are displayed on top of each other (last message on top) during the fade animation and after complety faded in they pop to their right stacked place.

When I trigger this "loop function" again manually without reloading the page the messages would display correctly (fade in at the right place).

Hope, Ive explained this problem clearly - its only a cosmetic one, but it would be nice if this could be 100%.

Except of this - very nice script :)

Thanks,
Frank

**Comment by rubjo** [comment]
Did you find out about this issue? I am experiencing the same thing with multiple notifications on page load.

Thank you for making a really useful plugin!

**Comment by hperrin** [comment]
This happens if you create notices before document.body exists. (Like, you load PNotify and create them in a script in the <head> section. ) If you load PNotify at the end of the <body> tag and create all your notices there, this shouldn't happen any more.
