### ISSUE TITLE
Text is invalid if anything has been added to Array.prototype

### ISSUE THREAD

**Issue by ashipma** [sciactive/pnotify#165]
I have a few functions that were added to the Array class, such as a function for copying arrays, removing elements, and some other prototype functions. But if there are any prototype functions, the text of the notice becomes the body of one of the functions.

The issue is in the parseOptions method. The loop that iterates the properties of the optArray array uses a foreach style loop. If this is switched to a regular for loop based on the index of each item in the array, the issue is resolved. Is there a reason the array is being iterated as a foreach? This will grab all the properties and functions defined for the array object, in this case it was getting the prototype functions.

So the fix that I applied locally was to change this line in the parseOptions function:

``` javascript
    for (var curIndex in optArray) {
```

to this:

``` javascript
    for (var curIndex = 0; curIndex < optArray.length; curIndex++) {
```

and that worked. But is there a reason it has to be a foreach?

Thanks

**Comment by Montoya** [comment]
I just ran into the same problem. I have the following: 

    Array.prototype.sum = function(selector) {
          if (typeof selector !== 'function') {
              selector = function(item) {
                  return item;
              }
          }
          var sum = 0;
          for (var i = 0; i < this.length; i++) {
              sum += parseFloat(selector(this[i]));
          }
          return sum;
      };

The means all arrays have an extra function() in them. I think the best way to get around this would be to check that each value in the array is an object or not a function.

**Comment by dazinator** [comment]
I also just hit this. Thanks for pointing me in the right direction with a fix.

**Comment by hperrin** [comment]
Fixed in v4. Will check v3 later.

**Comment by hperrin** [comment]
Yep, this is fixed in v3.
