### ISSUE TITLE
Closing notification not shown

### ISSUE THREAD

**Issue by kahwooi** [sciactive/pnotify#167]
The notification does not have the close button with the following code:

```
         new PNotify({
                title: 'Successful',
                text: 'User settings has been successfully save.',
                styling: "bootstrap3",
                type: "info",
                icon: 'glyphicon glyphicon-ok'
            });
```

**Comment by michnath** [comment]
I think we got the same problem.
Are you working with angularjs + requirejs / bootstrap3 + fontawesome?

This is my issue, https://github.com/sciactive/pnotify/issues/170

**Comment by kahwooi** [comment]
Yes, I am using it with  bootstrap3 + fontawesome.

**Comment by michnath** [comment]
Are you using it with angularJs and/or requireJS?

Have you tried to include this line:
PNotify.prototype.options.styling = "fontawesome";
mentioned on the readme part?

I did and it had no effect :(

**Comment by hperrin** [comment]
Have you included the buttons module, and have you checked to see if the element is being created, but not visible?

**Comment by ambischof** [comment]
I am including the buttons module and am using RequireJS, Bootstrap3 and fontawesome and the element for the button is not being created.

I have tried styling using both bootstrap3 and fontawesome.

**Comment by codymullins** [comment]
@hperrin looks like this can be closed

**Comment by a497988** [comment]
Bump...I am having this issue. I have tried including the following in my scripts:
        "../node_modules/pnotify/dist/pnotify.js",
        "../node_modules/pnotify/dist/pnotify.buttons.js",
        "../node_modules/pnotify/dist/pnotify.callbacks.js",
        "../node_modules/pnotify/dist/pnotify.confirm.js",
        "../node_modules/pnotify/dist/pnotify.history.js"

and my button config has the button reference set to true:
new PNotify({ 
	  	buttons: { close: true }, 
	  	icon: 'true', 
	  	animate: { animate: true, in_class: 'fadeInRight', out_class: 'zoomOut'}, 
	  	animate_speed: 'fast', 
	  	width: '400', 
	  	title: 'Success!', 
	  	text: message, 
	  	type: 'success' })

But the buttons still do not show up. All relevant styles are included to match my imported scripts, but I am unable to get it to work. Is there a fix for this yet?

**Comment by hperrin** [comment]
@a497988 If you're using RequireJS, make sure you're requiring both 'pnotify' and 'pnotify.buttons'.

**Comment by a497988** [comment]
I am using Angular2 and I have both buttons and pnotify defined as such:
        "../node_modules/pnotify/dist/pnotify.js",
        "../node_modules/pnotify/dist/pnotify.buttons.js",
        "../node_modules/pnotify/dist/pnotify.callbacks.js",
        "../node_modules/pnotify/dist/pnotify.confirm.js",
        "../node_modules/pnotify/dist/pnotify.nonblock.js",
        "../node_modules/pnotify/dist/pnotify.history.js"

Still no buttons, the HTML isn't being generated for them, so it isn't a css issue, and the notifications appear so I believe I am referencing it correctly. I am using V3.2.1

**Comment by tnusraddinov** [comment]
```
import 'pnotify/dist/pnotify.css'
import 'pnotify/dist/pnotify.brighttheme.css'
import 'pnotify/dist/pnotify.buttons.css'
import 'pnotify/dist/pnotify.history.css'
import 'pnotify/dist/pnotify.mobile.css'
import 'pnotify/dist/pnotify.nonblock.css'
import 'pnotify/dist/pnotify.confirm.js'
import 'pnotify/dist/pnotify.buttons.js'  <-- importing this line shows close buttons
```
