### ISSUE TITLE
how to set focus on ok button ??

### ISSUE THREAD

**Issue by Deepak690** [sciactive/pnotify#168]
how to set focus on ok button ??

**Comment by kafeltz** [comment]
When you click on a button, it does get focused.
I did not understand your question.

**Comment by Deepak690** [comment]
function AlertAskOk(Heading, Message, type, okclick) {
            var modal_overlay;

            info_box = $.pnotify({
                title: Heading,
                text: Message,
                type: type,
                buttons: 'ok',
                okclick: okclick,

                icon: "picon picon-object-order-raise",
                delay: 20000,
                history: false,
                stack: false,
                //nonblock: true,
                before_open: function (pnotify)
                {
                    //  $("btn-inverse").focus();
                    // Position this notice in the center of the screen.
                    pnotify.css({
                        "top": ($(window).height() / 2) - (pnotify.height() / 2),
                        "left": ($(window).width() / 2) - (pnotify.width() / 2)
                    });
                    // Make a modal screen overlay.
                    modal_overlay = $("<div />", {
                        "class": "ui-widget-overlay",
                        "css": {
                            "display": "none",
                            "position": "fixed",
                            "top": "0",
                            "width": "5000px",
                            "bottom": "0",
                            "right": "0",
                            "left": "0",
                            "cursor": "pointer"

                        }
                    }).appendTo("body").fadeIn("fast");
                },

                //....

                //after_open: function (ui) {
                //    $(".btn", ui.container).focus();
                //},
                //....

                before_close: function () {
                    modal_overlay.fadeOut("fast");
                }
            });

        }

this is my code. i want to set focus on ok button when dialog box open

**Comment by hperrin** [comment]
Try changing your commented code to:

```js
setTimeout(function(){$(".btn:first-child", ui.container).focus()}, 100);
```

**Comment by hperrin** [comment]
Let me know if that works for you.
