### ISSUE TITLE
Buttons and Confirm module not working

### ISSUE THREAD

**Issue by michnath** [sciactive/pnotify#170]
I'm working with angularjs, requirejs, bootstrap3 + fontawesome.
PNotify core works great; but everytime I work with buttons and confirm, the buttons wouldn't show up.

I installed PNotify using bower and I included all of modules (pnotify.core.js and all of its js modules) on my app library.

This is how I configure my requireJS:
```
require.config({
    baseUrl: '/assets/angular',
    paths: {
        pnotify: 'libs/pnotify/pnotify.core',
        // pnotifyButtons: 'libs/pnotify/pnotify.buttons', --> I tried to include the modules but it had no effect
        // pnotifyConfirm: 'libs/pnotify/pnotify.confirm',  --> I tried to include the modules but it had no effect
    }
});
```

This is how I call Pnotify
```
$scope.deleteData = function() {
  var confirmNotice = new Pnotify({
        text: 'Are you sure to delete this data?',
        type: 'notice',
        icon: false,
        buttons: {
            closer: false,
            sticker: false
          },
        confirm: {confirm:true}
      });
      confirmNotice.get().on('pnotify.confirm', function() {
          alert('Ok, cool.');
      });
      confirmNotice.get().on('pnotify.cancel', function() {
          alert('Oh ok. Chicken, I see.');
      });
};
```
It just returned a 'plain' notification without any buttons on it

PS:
- I have included this code on my app init section:
PNotify.prototype.options.styling = "fontawesome";
- I tried to download PNotify from its site (pnotify.custom.min.js) and it returned the same result (buttons not showing)

**Comment by robertftw** [comment]
Same problem for me :(

**Comment by cadecannon** [comment]
In case anyone else lands here:

```javascript
    paths: {
        pnotify: '<path-to-pnotify>/pnotify.core',
        // pnotifyButtons: '<path-to-pnotify>/pnotify.buttons',
        // pnotifyConfirm: '<path-to-pnotify>/pnotify.confirm',
    }
```
should be:
```javascript
    paths: {
        pnotify: '<path-to-pnotify>/pnotify.core',
        'pnotify.buttons': '<path-to-pnotify>/pnotify.buttons',
        'pnotify.confirm': '<path-to-pnotify>/pnotify.confirm',
    }
```
The name of those modules are important.

**Comment by hperrin** [comment]
I'm going to close this. If you're still having the same problem, feel free to reopen it.

**Comment by MageryThemes** [comment]
If you work with RequireJS, then you should require both components: 'pnotify' and 'pnotify.buttons'

**Comment by MRO60** [comment]
I'm sure it's because I'm an idiot, but I interpreted this incorrectly from the README when trying to get buttons to display using a confirmation:
version 5.2
Under **Confirm Module**
```
PNotifyConfirm.defaults = {
confirm: false
Make a confirmation box.
...
```
I assumed that the Confirm Defaults would be set to confirm and that I would not be expected to set this default value to **true** in order to get the buttons to display.  In my mind I somehow figured the confirm : false setting was going to force a human interaction and therefore a confirm dialog with buttons ... ya know, for a human.  

But that's my mind, which requires another manual and obviously a lot more reading.
