### ISSUE TITLE
Extend delay on click in desktop notifications

### ISSUE THREAD

**Issue by tehspede** [sciactive/pnotify#171]
Hi!

Is there a way to extend the delay of desktop notifications when they are clicked anywhere except the close button?

**Comment by hperrin** [comment]
You can turn mouse resetting off, then have a click event reset the timer.

**Comment by tehspede** [comment]
Could you provide an example of resetting the timer?

**Comment by hperrin** [comment]
Unfortunately, you can't programmatically extend the duration of a desktop notice. (The spec doesn't have a way to do this.) The best you can do is to close the notice and reopen it.
