### ISSUE TITLE
PNotify.removeAll not working

### ISSUE THREAD

**Issue by askone** [sciactive/pnotify#173]
When you want to delete all notifications from the collection of only a part of them is removed. The problem concerns the application of the method $ .each and Array.splice together. The solution is to modify the removeAll method to the form:

``` javascript
removeAll: function () {
   var i = PNotify.notices.length;
   while (i--) {
       if (PNotify.notices[i].remove) {
            PNotify.notices[i].remove(false);
       }
    }
}
```

**Comment by hperrin** [comment]
Fixed in develop branch. (v4)
