### ISSUE TITLE
Do you want to be an official PNotify developer?

### ISSUE THREAD

**Issue by hperrin** [sciactive/pnotify#175]
I've seen a lot of users answering issues on here and providing pull requests. I'd love to delegate some power to help develop PNotify. Let me know if you are interested in helping manage and improve the official codebase.

**Comment by Jeyveen7** [comment]
I might be interested.

**Comment by hperrin** [comment]
@Jeyveen7 Have you made any pull requests?

**Comment by Jeyveen7** [comment]
Not yet

**Comment by hperrin** [comment]
@Jeyveen7 Would you like to help out with some of the issues? Just going through and answering questions, and labelling things correctly.

**Comment by jonnyboy** [comment]
I would be interested. I like to contribute to projects that I use.

**Comment by djmattyg007** [comment]
I'm interested. I've started using this project recently and would like to ensure it is maintained going forward.

**Comment by hperrin** [comment]
@djmattyg007, @ghost, Are you still interested? Can you take a look at the bugs with the `ready` label, and see if you can take any on?
