### ISSUE TITLE
Download script builds broken PNotify (pnotify.custom.js)?

### ISSUE THREAD

**Issue by smajl** [sciactive/pnotify#177]
If you use "Download PNotify 2.0" on the main page, then you get something strange and broken. At least **callbacks don't work**... Also the script has a 2.0.1 version label, but **does not containt recent bug fixes from the latest version**.

**Comment by Rigoberto-Vazquez** [comment]
+1

**Comment by hperrin** [comment]
@Rigoberto-Vazquez Please try again and let me know if you are still seeing the problem.
