### ISSUE TITLE
Unable to close the pnotify

### ISSUE THREAD

**Issue by yiqiang** [sciactive/pnotify#179]
It is very weird i cant seem able to close the pnotify

var effect_in = 'scale',
easing_in = 'easeOutElastic',
effect_out = 'scale',
easing_out = 'easeInCubic',
speed = 700;
var options_in = {
    easing: easing_in
},
options_out = {
    easing: easing_out
};
if (effect_in == 'scale') options_in.percent = 100;
if (effect_out == 'scale') options_out.percent = 0;

function send_msg(status,heading,message){
    var notice=new PNotify({
        title: heading,
        text: message,
        type: status,
        animate_speed: speed,
        animation: {
            'effect_in': effect_in,
            'options_in': options_in,
            'effect_out': effect_out,
            'options_out': options_out
        },
        buttons: {
            sticker: false
        }
    });
    notice.get().click(function() {
        notice.remove();
    });
}

it just zoom become smaller

**Comment by hperrin** [comment]
jQuery UI support is being removed in favor of Animation.css support. Most likely, all JavaScript based animations will be removed.

**Comment by KrishnaPG** [comment]
Sorry to hear that. What about the "JQuery Transfer effect"? Not sure if Animation.css can do such equivalents.

For example, I am presently trying to use "transfer effect" to make it look like the notification, upon close,  animates into a  notification center (a simple icon on top navbar). 

If the plan is to replace JQuery UI with animation.css, any help on how to achieve similar effect with animation.css would be of great help. The goal is to make the user feel that the notification can be accessed later from the notification center (hence the animation 'transfer effect' upon close)
