### ISSUE TITLE
Feature request: Add click event for notifications

### ISSUE THREAD

**Issue by aensley** [sciactive/pnotify#18]
It would be nice to be able to specify a click handling callback for each notification (or a global one I suppose). The handler would be called any time the notification is clicked unless the user is clicking the sticker or close buttons.

This functionality could be used to perform the following actions:
- **Close** the notification - Easier method to dismiss a notification than searching for the tiny button.
- **Stick**/**Unstick** the notification - Easier method than searching for the button.
- Take user to resource mentioned in the notification (either another **URL** or a **hashtag** for something on the current page).
- Display more detailed content.
- Maximize the notification.
- Overlay the rest of the page with a blurring layer so that the notification is highlighted (i.e. like a jQuery modal dialog).
- Some combination of the above.

Of course I'm not asking that those actions be built-in. Those are just a few ideas I came up with that would be possible with a click handler and would really be nice to be able to do.

Examples:

``` javascript
$.pnotify({
    title: 'New message',
    text: 'You have a new message from Joe',
    click: function(){
        window.location.href = "http://mysite.com/messages/messageFromJoeId";
    }
});
```

``` javascript
$.pnotify({
    title: 'New message',
    text: 'You have a new message from Joe',
    click: function(){
        $(this).append('<div class="messageContents">Hey man, how\'s it going?</div>');
    }
});
```

**Comment by chfw** [comment]
Please note that since version 2.1, pnotify_remove() of a PNotify instance is renamed to remove()
