### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by euprogramador** [sciactive/pnotify#180]
Please add npm support install

**Comment by Nicolab** [comment]
+1

**Comment by suin** [comment]
+1

**Comment by Fauxide** [comment]
:+1: I don't know how this hasn't been done yet

**Comment by zdila** [comment]
+1

**Comment by ximex** [comment]
:+1:

**Comment by adjeteyadjei** [comment]
:+1:

**Comment by hperrin** [comment]
Haha. I can see this is a very popular request. I'll include it in the next version.

**Comment by rafaeleyng** [comment]
:+1:

**Comment by StephaneTrebel** [comment]
:+1:

**Comment by sgentile** [comment]
Still no add ?

**Comment by hperrin** [comment]
I haven't released a new version yet.

**Comment by sota1235** [comment]
:+1:

**Comment by hperrin** [comment]
I forgot to close this after the release. PNotify is on NPM!

https://www.npmjs.com/package/pnotify
