### ISSUE TITLE
notifications often animate from the middle of the screen to the right top.

### ISSUE THREAD

**Issue by shamroze** [sciactive/pnotify#187]
Hello,

The notifications seems to work well enough however i have found this strange issue in the animation of the notficiation. I have this one large notification, and few little ones . When i trigger the large notification on my laptop it appears right in the middle of the screen and then it animates and move to right of the screen but this doesnt happen when I then trigger any other notification which is fairly small, they pop to middle right of the screen and goes up to the right corner. However when i switch to a bigger screen , the large one and even the small one pops to the middle right and goes to the top right corner. Can you please let me know how can i make it consistent , ideally i would like all my notifications to animate on the middle of the screen and then goes to the right top as the large notification is working. This is my current setup for notifications. 

```
                title: title,
                text: message,
                type: type,
                mouse_reset: false,
                delay: _delay,
                buttons: {
                    closer : false,
                    sticker: true,
                    sticker_hover : false
                },
                confirm : {
                    confirm :true,
                    buttons: [{
                        text : 'close',
                        addClass : 'disable-outline ' + close_btn_color,
                        click : function (notice) {
                            notice.remove();
                        }
                    }]
                }
```

**Comment by hperrin** [comment]
I'm not sure what you're trying to do. Do you want these notices to appear in the middle of the screen, or is this unwanted behavior?

**Comment by bjornhanson** [comment]
I think I'm seeing a similar problem. I have a notification creating function that creates notifications in a top right stack. The first notification shows up in the top right, as expected. If I let that disappear, the next notification shows up down further on the page (where the second notification would be if more than one were stacked) and then it slides up to where the first notification originally displayed. Only the first notification actually shows up where it should; the rest start one spot lower and slide up to the position they stay in until they disappear. This even happens with a simple notification, with just `title` and `text` defined. Any ideas? Thanks!

**Comment by hperrin** [comment]
Fixed in develop branch. (v4)
