### ISSUE TITLE
stack-bar-bottom only defined on the index.html?

### ISSUE THREAD

**Issue by ryansoper** [sciactive/pnotify#190]
Hi all,

I'm using the PNotify library at the moment and had some difficulty getting the stack-bar-bottom to style correctly. I noted there didn't appear to be a stack-bar-bottom class in any of the CSS files I had, and initially I believed that Bower had pulled through a really lightweight version of the library. This is not the case, but it appears the stack-bar-bottom class is only defined INLINE on the index.html page. Surely it is a better idea to define this in a css file, like core or even a new stacks.css file?
The project i'm working on are not fond of Inline CSS, and so I have added the stack-bar-bottom to the core class.

Am I missing a trick, or is this really the only place the class is defined?

**Comment by Doskious** [comment]
The same appears to hold true for the stack-bar-top class and all stack variable definitions, I downloaded the most complete package manually to verify.  Additionally, the js/css download left me without any of the necessary stack variable declarations for the "stack: stack_bar_top" or "stack: stack_bottomleft" options.

It appears that despite documentation to the contrary, stacks are not, in fact, included in PNotify Core at this time.

**Comment by hperrin** [comment]
Fixed in develop branch. (v4) Stacks no longer use classes for initial positioning.
