### ISSUE TITLE
Adjust initial position of the notification

### ISSUE THREAD

**Issue by jackyliang** [sciactive/pnotify#192]
I am trying to adjust the initial position of my PNotify notification. As you can see in the image, the notification blocks my search bar. I would like to bring the initial position of the notification down by around 50px so it doesn't block the search bar.

I've been Googling this issue for a long time now, but with no result:

I've tried:

1. Changing the CSS of the notification by adding a `margin-top: 50px`

2. Under the [docs](http://sciactive.github.io/pnotify/#demos-modules) there are custom classes to change the initial position, but they were all custom-defined classes like `stack_bar_top` or `stack_bar_bottom`. I would like to adjust these values myself.

3. This answer on the [Github](https://github.com/sciactive/pnotify/issues/46) page but I was thrown the `no such class as pnotify.css` error

[![enter image description here][1]][1]

This is my code for PNotify at the moment:

        function notification(text, type) {
            new PNotify({
                text: text,
                type: type,
                animation: 'slide',
                delay: 3000,
                top:"500px",
                min_height: "16px",
                animate_speed: 400,
                text_escape: true,
                nonblock: {
                    nonblock: true,
                    nonblock_opacity: .1
                },
                buttons: {
                    show_on_nonblock: true
                },
                before_open: function(PNotify){
                    PNotify.css({
                        "top":"50px"
                    });
                }
            });
        }

I checked out the CSS, and it seems `ui-pnotify` is in charge of the positioning. The default is `top: 25px`.

I made a new class in my CSS and called it:

    .ui-pnotify {
      top: 50px;
    }

Didn't seem to work, however. 

  [1]: http://i.stack.imgur.com/0AwHX.png

**Comment by kalifa17** [comment]
+1

**Comment by kalifa17** [comment]
I found a solution that works adding a different stack:

new PNotify({
            title: 'Confirmation Needed',
            text: 'Do you want to save?',
            icon: 'glyphicon glyphicon-question-sign',
            stack:  {"dir1": "down", "dir2": "right", "firstpos1": ($(window).height()/2 -150), "firstpos2": ($(window).width()/2 - 150)}
        });

Hope that helps.

**Comment by jackyliang** [comment]
When you use a second notification, it simply appears on top of the existing one.

**Comment by jackyliang** [comment]
@phelipealves I understand this - not sure how it helps solve the problem in any way.

**Comment by 1ap1** [comment]
@jackyliang

Wiith kalifa17's code you're creating a new stack each time. This won't overlap.

var stack_center = {"dir1": "down", "dir2": "right", "firstpos1": ($(window).height()/2 -150), "firstpos2": ($(window).width()/2 - 150)};

$.pnotify({
	title: 'Confirmation Needed',
	text: 'Do you want to save?',
	icon: 'glyphicon glyphicon-question-sign',
	addclass: "stack_center",
	stack: stack_center
});

$.pnotify({
	title: 'Confirmation Needed',
	text: 'Do you want to save?',
	icon: 'glyphicon glyphicon-question-sign',
	addclass: "stack_center",
	stack: stack_center
});

**Comment by hperrin** [comment]
Thank you @kalifa17, @phelipealves, and @1ap1 for you help with @jackyliang's issue. Yes, the recommended solution is to create a new stack (or alter the default stack at `PNotify.prototype.options.stack`) and set the `firstpos1` property to wherever you would like the notice positioned. As per @1ap1's answer, if you create a new stack, you must assign the stack object to a variable, and use this variable in each PNotify call. This is because PNotify uses the actual stack variable to hold each notice in the stack. If you pass in an object literal as the stack, a new stack is created each time, and that new stack is assigned the one notice.

If you'd like to alter the default stack to simplify the solution, you can use this code:
```js
PNotify.prototype.options.stack.firstpos1 = 150; // or whatever pixel value you want.
```
Then you can create notices without defining a stack.
