### ISSUE TITLE
2.1.0 Confirm Dialog shows an undefined button if you modify Array.prototype

### ISSUE THREAD

**Issue by zweissman** [sciactive/pnotify#195]
I was just upgrading to 2.1.0 and saw a weird extra button in my confirm dialog that was not there in the 2.0.1 version. 

![image](https://cloud.githubusercontent.com/assets/4612688/9825632/9f2564d6-58a2-11e5-93f8-81e886223a72.png)

It looks like the culprit is my code base adding a Array.prototype.move function as when I comment that out, it goes away.

Looks like the code that creates the buttons changed from 

2.0.1 working

    for (var i = 0; i < options.buttons.length; i++) {

to 2.1.0 not working

    for (var i in options.buttons) {

I don't see much if any other changes in the code other than this.

I've gone and just rewritten the move code since it was a polyfil that was probably not needed anyway. But if possible, it might save some headaches if you could change your for loop back to the 2.0.1 version.

**Comment by cratu** [comment]
https://github.com/sciactive/pnotify/pull/196 fixes that, maybe 
```for (var i = 0; i < options.buttons.length; i++)```
will be better than
```if(typeof btn === "function") continue;```

**Comment by hperrin** [comment]
This is fixed now. You can see the fix here:
https://github.com/sciactive/pnotify/blob/e6a3adbcce7e206e951a59d16b33a74d8dbea50a/src/pnotify.confirm.js#L88

**Comment by hperrin** [comment]
It's not the best solution, as it adds another O(n) time function to every button that's defined, but I think it's justified, considering the likelihood (or lack thereof) of people adding a high number of buttons. It also allows a button to be defined in a string key. Unfortunately, it doesn't guarantee the order of the buttons. Do you guys have a suggestion of how to solve that problem?

**Comment by zweissman** [comment]
Thanks. I'll check it out as soon as I can.

**Comment by ekawalec** [comment]
I've got the same problem - any other solutions???

**Comment by cratu** [comment]
@ekawalec https://github.com/sciactive/pnotify/blob/e6a3adbcce7e206e951a59d16b33a74d8dbea50a/src/pnotify.confirm.js#L88 - works

**Comment by ekawalec** [comment]
version number doesn't update local bower storage ... so .... change it, please ...

**Comment by ekawalec** [comment]
./bower update -f pnotify ..... still got old & not fixed version .....

**Comment by hperrin** [comment]
The fix hasn't been in a release yet.
