### ISSUE TITLE
Pnotify confim dialog not showing buttons

### ISSUE THREAD

**Issue by paveytel** [sciactive/pnotify#197]
I am using angularjs and added this in my code, copied directly from Pnotify

 $(function(){
                    (new PNotify({
                        title: 'Confirmation Needed',
                        text: 'Are you sure?',
                        icon: 'glyphicon glyphicon-question-sign',
                        hide: false,
                        confirm: {
                            confirm: true
                        },
                        buttons: {
                            closer: false,
                            sticker: false
                        },
                        history: {
                            history: false
                        }
                    })).get().on('pnotify.confirm', function() {
                            alert('Ok, cool.');
                        }).on('pnotify.cancel', function() {
                            alert('Oh ok. Chicken, I see.');
                        });
                });

but the Ok and Cancel buttons dont show up. Any suggestions are welcomed, thanks

**Comment by hperrin** [comment]
Did you add the buttons module?

**Comment by hperrin** [comment]
Or the confirm module.
