### ISSUE TITLE
Not an issue but Requests.

### ISSUE THREAD

**Issue by vdeapps** [sciactive/pnotify#201]
Hi. Great job for your PNotify.

Can you add, like min_height an option 'min_width'. I want to fix a minimal size for my notification but not a maximal size.

How can I add my own icons closer an sticker ? Like 'icon' option can you add 'icon_sticker', 'icon_closer' ?

Thanks

**Comment by hperrin** [comment]
You can define a minimum width with CSS programmatically, like this:

```js
(new PNotify({
  title:"Width Notice",
  text:"I'm really wide."
})).get().css({
  "min-width":"500px",
  "width":"auto"
});
```

You can also change the icons used by the closer and sticker buttons by changing the styling object you're using. So, if you are using the "bootstrap3" styling object, you'd do something like this:

```js
PNotify.styling.bootstrap3.closer = "glyphicon glyphicon-remove";
PNotify.styling.bootstrap3.pin_up = "glyphicon glyphicon-pause";
PNotify.styling.bootstrap3.pin_down = "glyphicon glyphicon-play";
```

**Comment by hperrin** [comment]
I hope that helps. :D

**Comment by vdeapps** [comment]
Thanks, I'll try it.

**Comment by vdeapps** [comment]
It's OK with CSS rule:

.ui-pnotify.custom{
	min-width: 250px;
	width: auto !important;
}

Thanks.
