### ISSUE TITLE
Selecting the 'Animate' option from the download doesn't generate a download

### ISSUE THREAD

**Issue by fc** [sciactive/pnotify#204]
If I select the 'Animate' checkbox for downloading the source then click Get the JS/CSS it will say:

```
Your request could not be completed because a file you requested is invalid.
```

URL that is generated:
https://sciactive.com/pnotify/buildcustom.php?mode=js&min=true&modules=desktop-buttons-mobile-animate&cff=.js

**Comment by hperrin** [comment]
It hasn't been released yet. There is a notice about it in the bottom left corner.
