### ISSUE TITLE
Unable to download pnotify

### ISSUE THREAD

**Issue by RyanMadsen** [sciactive/pnotify#210]
After clicking Get Javascript or Get CSS I get linked to a page that displays: 

Warning: file_get_contents(dist/pnotify.css): failed to open stream: No such file or directory in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /home/content/35/12303835/repos/pnotify/buildcustom.php:25) in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 33
Your request could not be completed because a file you requested is invalid.

**Comment by bertmert** [comment]
Confirmed. No download possible at
https://sciactive.com/pnotify/

**Comment by wodCZ** [comment]
Any update? 

ping @hperrin

**Comment by wodCZ** [comment]
"Workaround": you can uncheck `Minify the Script and Stylesheet`, works then.

**Comment by hperrin** [comment]
Sorry, my bad. It's fixed now. Thanks for reporting this.
