### ISSUE TITLE
Buttons and animate not working ?

### ISSUE THREAD

**Issue by SebT** [sciactive/pnotify#211]
Hi,

I have the following code: 

``` javascript
new PNotify({
    type: "info",
    icon: "fa fa-check",
    title: "My title",
    text: "My text",
    buttons: {
      close: true,
      close_hover: true
    },
    animate: {
      animate: true,
      in_class: 'zoomInLeft',
      out_class: 'zoomOutRight'
    }
  });
```

But no button is displayed on hover and the default fade animation is used.

I'm using bootstrap3 + fontawesome.

I'm using webpack and I included lib/pnotify.js, ib/pnotify.animate.js, ib/pnotify.buttons.js, lib/pnotify.css, lib/pnotify.buttons.css

**Comment by Izopi4a** [comment]
check this one : https://github.com/sciactive/pnotify/issues/209

for the buttons, make sure you include buttons.js

**Comment by SebT** [comment]
Yes I forgot to mention I did include animate.css.

Actually i import buttons and animate (ex: `import 'pnotify/dist/pnotify.animate.js'`) JS files from webpack and this is what fails. I have no errors but it seems the files are not included, whereas when I copy their content in one of my JS files it works... 

So it has nothing to do with the lib, I guess it's just webpack/babel (as usual --')
