### ISSUE TITLE
A way to get the object of existing notification

### ISSUE THREAD

**Issue by devmarwen** [sciactive/pnotify#213]
I'm trying to update an existing notification via realtime pushes, so whenever there is a an event I have to update something about the notification: progressbar, percentage, title, width ...
```coffeescript
options.title = 'Done!'
options.addclass = 'bg-success'
options.icon = 'icon-check'
options.opacity = 1

## Here how do i get the notice object of the notice/notification
notice.update options
```

One way is to use a `global variable` but is there a way to get the object from the existing one.

**Comment by hperrin** [comment]
Yes, there is. It's not documented, but there is an array called `PNotify.notices` that contains all notices.
