### ISSUE TITLE
Do not work dist downloading from http://sciactive.com/pnotify/

### ISSUE THREAD

**Issue by ThePeton** [sciactive/pnotify#215]
Hi

I am trying to download the PNotify 3 from http://sciactive.com/pnotify/ and getting the error message:
"Warning: file_get_contents(dist/pnotify.js): failed to open stream: No such file or directory in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /home/content/35/12303835/repos/pnotify/buildcustom.php:25) in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 33
Your request could not be completed because a file you requested is invalid."

Check please this error. 

Exact steps:
1. Go to http://sciactive.com/pnotify/
2. Click button "Download PNotify 3"
3. Click button "Get the JavaScript" in popup form

**Comment by bertmert** [comment]
Known.
https://github.com/sciactive/pnotify/issues/210

**Comment by scream4ik** [comment]
Same issue with https

**Comment by hperrin** [comment]
Sorry, my bad. It's fixed now. Thanks for reporting this.
