### ISSUE TITLE
While downloading click, it gives error

### ISSUE THREAD

**Issue by emran** [sciactive/pnotify#216]
The following Error is appear while going to download:
===========================================

Warning: file_get_contents(dist/pnotify.js): failed to open stream: No such file or directory in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /home/content/35/12303835/repos/pnotify/buildcustom.php:25) in /home/content/35/12303835/repos/pnotify/buildcustom.php on line 33
Your request could not be completed because a file you requested is invalid.

**Comment by ThePeton** [comment]
3-rd ticket :)
Other two - #210 and #215.

**Comment by hperrin** [comment]
Sorry, my bad. It's fixed now. Thanks for reporting this.
