### ISSUE TITLE
Get this error when generating custom stylesheet and javascript

### ISSUE THREAD

**Issue by muhammad-ihsan** [sciactive/pnotify#218]
![Error](http://i.imgur.com/JxzXFCI.png)

**Comment by muhammad-ihsan** [comment]
close, same problem here [#215](https://github.com/sciactive/pnotify/issues/215) & [#210](https://github.com/sciactive/pnotify/issues/210)

**Comment by hperrin** [comment]
Sorry, my bad. It's fixed now. Thanks for reporting this.
