### ISSUE TITLE
Stack not working when using PNotify as AngularJS directive

### ISSUE THREAD

**Issue by rkaehlert** [sciactive/pnotify#220]
I want to use this awesome plugin as a angular-js-directive. The problem is, if i add two instances of this directive to my website, the stack gets somehow resetted and the two notifications are displayed on top of each other. This is the link of my directive:

link: function ($scope) {
            var stack_bar_top = {"dir1": "down", "dir2": "right", "push": "top", "spacing1": 0, "spacing2": 0};

            var opts_stack_bar_top = {
                title: $scope.title,
                addclass: "stack-bar-top",
                width: "100%",
                stack: stack_bar_top,
                buttons: {
                    closer_hover: false,
                    sticker: false,
                    classes: {
                        closer: "vw-icon-close",
                    }
                }
            };

            switch ($scope.type) {
            case TYPES.SUCCESS:
                opts_stack_bar_top.icon = "vw-icon-check";
                opts_stack_bar_top.hide = true;
                opts_stack_bar_top.delay = 5000;
                break;
            case TYPES.ERROR:
                opts_stack_bar_top.icon = "vw-icon-cwp-help";
                opts_stack_bar_top.hide = false;
                break;
            case TYPES.ATTENTION:
                break;
            case TYPES.DWA:
                break;
            }

            new PNotify(opts_stack_bar_top);
        }

Would be very great if someone can help me here. Thanks a lot!

**Comment by hperrin** [comment]
You need to make your service a singleton, and set up the stack object during your singleton setup. Then you can provide a function that uses that stack.

The problem is that you are giving a new object as your stack for each PNotify call. Read through this part of the readme:
https://github.com/sciactive/pnotify#stacks
