### ISSUE TITLE
Source code for Modal Confirm Dialog not viewable in demo

### ISSUE THREAD

**Issue by NightOwl888** [sciactive/pnotify#221]
In your [demos page](https://sciactive.github.io/pnotify/#demos-simple), it is not possible to view the source for the modal confirm dialog because the dialog is, well, modal. So there is no way to click the "View Source" link under the modal overlay. Once you click a button on the dialog, the "View Source" link is hidden from view.

**Comment by domzinhuu** [comment]
I had another problem with the modal confirm, i copy the code of the button and yes work... but when i confirm or cancel the notify disappear and the modal dont... so i need refresh the page

**Comment by NightOwl888** [comment]
@domzinhuu - That is the same issue as #214 and #225. You need to add the History module or the background does not disappear. Seems like a bug, but at least there is a workaround.

**Comment by domzinhuu** [comment]
\o thanks

Em sex, 12 de fev de 2016 09:47, Shad Storhaug <notifications@github.com>
escreveu:

**Comment by audiolion** [comment]
seconded, you can't view the source of any modal pnotify options

**Comment by hperrin** [comment]
:-/ Well, you can, but you have to tab to the option with the keyboard. I need to fix this...

**Comment by hperrin** [comment]
Fixed in develop branch. (v4) You can see it live on the development demo site.
