### ISSUE TITLE
Avoid duplicate notifications

### ISSUE THREAD

**Issue by garubi** [sciactive/pnotify#228]
I would like to avoid that a notification will be displayed if another notification is already on screen...
How can I check it?
I looked in the examples but haven't found anything ... 

Thank you 
Stefano

**Comment by scream4ik** [comment]
https://github.com/sciactive/pnotify/blob/master/src/pnotify.desktop.js#L52-L55

**Comment by garubi** [comment]
@scream4ik thank you, I'm going to try it

**Comment by garubi** [comment]
@scream4ik I checked the code and the docs but still I can't understand how to use 'tag' to prevent duplicate notification on the screen.
I added `tag: 'mytag'` but still I get duplicate notification. 
moreover, it looks like the 'tag' is only for desktop notifications and not for "in browser" notification

I'm sorry to bother you, but can you show me a practical example of how to avoid duplicate notifications?
Thank you very much!!

**Comment by scream4ik** [comment]
My js:
```
function desktop_notify(msg) {
    (new PNotify({
        title: msg.pnotify_title,
        text: msg.pnotify_text,
        hide: false,
        buttons: {
            sticker: false
        },
        desktop: {
            desktop: true,
            tag: msg.pnotify_tag
        }
    })).get().click(function(e) {
        if ($('.ui-pnotify-closer, .ui-pnotify-sticker, .ui-pnotify-closer *, .ui-pnotify-sticker *').is(e.target)) return;
        if (msg.pnotify_url)
            window.open(msg.pnotify_url, '_blank')
    });
}
```
From backend i generate unique tag (msg.pnotify_tag)

I test it only for desktop notifications

**Comment by garubi** [comment]
Wow, thank you for the fast answer! ;-)
I see... for the desktop notification now I understand.
In the meantime for the "in browser" notification i solved siply adding a specific class to the notification(with `addclass`), then checking if an element with that clas is already present. If present I don't add the new notification:
`if($('.newreq').length <1){
      var notice = new PNotify({
	title: 'My Title',
	text: 'My message',
	type: 'info',
        addclass:  'my_unique_class',
	hide: false
});
`

**Comment by hperrin** [comment]
For PNotify 3, you can use `PNotify.removeAll()` before you open a notice. For PNotify 4, the history module now has a `maxInStack` option to do what you want.

**Comment by evolross** [comment]
Sadly in PNotify 5 there's extremely limited options for accessing the current set of notices that are being shown. In previous versions you could just call `PNotify.notices` and have full access to all the notices and their options. Now it forces you to use the DOM and hacks like `addClass` since you can't even access the `type`, `text`, etc. of a `notice`.

Added a new issue regarding this [How to get existing notice options in PNotify 5?](https://github.com/sciactive/pnotify/issues/421)
