### ISSUE TITLE
multiple modal confirm dialogs

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [sciactive/pnotify#229]
When open a modal confirm dialog and press "Enter", there will be multiple modal confirm dialogs

**Comment by hperrin** [comment]
If you're doing this on the demo page, it's because the dialog is not focused. That's a good catch. It certainly should be focused.

**Comment by hperrin** [comment]
I added a focus control option to the Confirm module, so now this is controllable.
https://github.com/sciactive/pnotify/commit/dbc603faaa68a10bb4e0b7d41e35813d979ae68e
