### ISSUE TITLE
When using stack-bottomright messages display one on the other, see sample code.

### ISSUE THREAD

**Issue by barakb** [sciactive/pnotify#23]
<h4>Benchmarking</h4>

```
                <button class="btn source" onclick="for (i=0; i!=10; i++) {$.pnotify({
                                            addclass: 'stack-bottomright',
                                            stack: {'dir1': 'up', 'dir2': 'left', 'firstpos1': 25, 'firstpos2': 25},
                    title: 'Regular Notice',
                    text: 'Check me out! I\'m a notice.'
                });}">10 Notices</button>
```

**Comment by gaurav-compumatrice** [comment]
Hi @kouts, 
it's help me partially, in my scenario, I have 6 different sections separately in one page, it is working fine if I am using addclass: "stack-topright" but not for stack-bottomright see below code.

// this is global variable
var stack_bottomright = {
                "dir1": "up",
                "dir2": "left",
                "firstpos1": 50,
                "firstpos2": 25
            };
//global variable end

PNotify.prototype.options.width = "325px";
PNotify.prototype.options.styling = "fontawesome";

                            new PNotify({
                                title: self.dataField.name + " section saved",
                                text: '',
                                type: 'success',
                                addclass: "stack-bottomright",
                                stack: stack_bottomright                                
                            });

**issue**:- if clicked all section separately the messages display one on the other (its overlapping)
