### ISSUE TITLE
Uncaught ReferenceError: PNotify is not defined

### ISSUE THREAD

**Issue by erikasland** [sciactive/pnotify#232]
I first installed PNotify using NPM like so...
`npm install pnotify --save` 

It shows that it installed fine in my packages.json file...
`"pnotify": "^3.0.0"`

I then put these two in my head like so...
`<head><script type="text/javascript" src="pnotify.custom.min.js"></script>
<link href="pnotify.custom.min.css" media="all" rel="stylesheet" type="text/css" /></head>`

I am getting the following error in my console in my google dev tools...
`GET http://localhost:8000/pnotify.custom.min.js`

When I call something like this using my jQuery...
`$(document).ready(function(){
                $(function(){
                    new PNotify({
                        title: 'Regular Notice',
                        text: 'Check me out! I\'m a notice.'
                    });
                });
            })`

And am getting the following...
`Uncaught ReferenceError: PNotify is not defined`
`GET http://localhost:8000/pnotify.custom.min.css`

Is this a bug, or am I just a noob? I would really like to use your product for a project I am doing if you could help me get it working. Thank you.

**Comment by KrishnaPG** [comment]
Getting the same error with https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.0.0/pnotify.min.js

**Comment by nicklello** [comment]
Have recently updated from PNotify 2.0.0 to 3.0.0 using a bundle generated via http://sciactive.com/pnotify/ and am getting this problem

**Comment by ahinkle** [comment]
Getting the same error as @nicklello. Please comment if you find a solution.

**Comment by djmattyg007** [comment]
Do you have multiple copies of jQuery on the page?

**Comment by nanadjei2** [comment]
Am Getting the same error.

**Comment by cripiLP** [comment]
I have the same issue, downloaded pnotify with all modules from [here](https://sciactive.github.io/pnotify/)

**Comment by itsykhovskyi** [comment]
try this
`window.PNotify = require('pnotify/src/pnotify');`

**Comment by hperrin** [comment]
pnotify.custom.min.js is what you would use if you had downloaded the file from the demo page. If you're installing it with NPM, you need to include the files in the `dist` directory instead.

**Comment by hperrin** [comment]
If anyone has a different problem, can you share your code, and I will take a look?

**Comment by RezaGhanbari** [comment]
Trying to use cdn that mentioned @KrishnaPG with this script in index.html file:
`
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.0.0/pnotify.min.js"></script>
<script type="text/javascript">
            function init_PNotify() {
            if( typeof (PNotify) === 'undefined'){ return; }
            new PNotify({
              title: "PNotify",
              type: "info",
              text: "Welcome. Try hovering over me. You can click things behind me, because I'm non-blocking.",
              nonblock: {
                  nonblock: true
              },
              addclass: 'dark',
              styling: 'bootstrap3',
              hide: false,
              before_close: function(PNotify) {
                PNotify.update({
                  title: PNotify.options.title + " - Enjoy your Stay",
                  before_close: null
                });

                PNotify.queueRemove();

                return false;
              }
            });

            };
            init_PNotify();
        </script>
`

**Comment by RezaGhanbari** [comment]
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.0.0/pnotify.min.js"></script>`

```
<script type="text/javascript">
            function init_PNotify() {
            if( typeof (PNotify) === 'undefined'){ return; }
            new PNotify({
              title: "PNotify",
              type: "info",
              text: "Welcome. Try hovering over me. You can click things behind me, because I'm non-blocking.",
              nonblock: {
                  nonblock: true
              },
              addclass: 'dark',
              styling: 'bootstrap3',
              hide: false,
              before_close: function(PNotify) {
                PNotify.update({
                  title: PNotify.options.title + " - Enjoy your Stay",
                  before_close: null
                });

                PNotify.queueRemove();

                return false;
              }
            });

            };
            init_PNotify();
        </script>
```
