### ISSUE TITLE
Create 'icon_container' in Class Variables

### ISSUE THREAD

**Issue by johnpozy** [sciactive/pnotify#233]
Same as `text_container` and `title_container`, the `icon_container` should also available in `notice` object. Later we can simply access it like `notice.icon_container` instead of `document.getElementsByClassName('ui-pnotify-icon')`.

![image](https://cloud.githubusercontent.com/assets/115924/13103192/29908466-d58f-11e5-9358-4dd90bc0768c.png)

I can make a PR if you want.

Thanks

**Comment by hperrin** [comment]
In v4, you will be able to use notice.refs.iconContainer.
