### ISSUE TITLE
HTML Tags

### ISSUE THREAD

**Issue by ghost** [sciactive/pnotify#236]
How do you, either, remove html tags for desktop notifications while leaving them intact for popups or parse html tags in desktop notifications as they are in popups?

Thank you

**Comment by jonnyboy** [comment]
I have, temporarily, stripped the html from the text before sending to pnotify. But I would like to be able to remove the hmtl only if desktop notification is used.

**Comment by MaxShv** [comment]
+1

**Comment by gkopylov** [comment]
You can do this by specifying different text for desktop(from https://github.com/sciactive/pnotify/pull/205):
```
desktop: {
  ...
  text: 'Some text only for desktop'
}
```

and for title you can use this PR https://github.com/sciactive/pnotify/pull/247 (I hope it'll be merged):
```
desktop: {
  ...
  title: 'Some title only for desktop'
}
```
