### ISSUE TITLE
bower.json main order

### ISSUE THREAD

**Issue by Sempiternity87** [sciactive/pnotify#239]
I'm using gulp to inject my file references into the page. Because of the current order of the bower main list, pnotify.animate.js, pnotify.buttons.js, pnotify.callbacks.js, and pnotify.confirm.js are being loaded before the main pnotify.js which is causing errors when the page loads because PNotify has not been created yet. Recommend moving pnotify.js to the top of the main list.

**Comment by bluespaghetti** [comment]
This is still an issue.

In the meantime, you can use bower overrides in your bower.json file to override theirs.

E.G:
```
"overrides": {
    "pnotify": {
      "main": [
        "dist/pnotify.css",
        "dist/pnotify.js",
        "dist/pnotify.animate.js",
        "dist/pnotify.brighttheme.css",
        "dist/pnotify.buttons.css",
        "dist/pnotify.buttons.js",
        "dist/pnotify.callbacks.js",
        "dist/pnotify.confirm.js",
        "dist/pnotify.desktop.js",
        "dist/pnotify.history.css",
        "dist/pnotify.history.js",
        "dist/pnotify.mobile.css",
        "dist/pnotify.mobile.js",
        "dist/pnotify.nonblock.js"
      ]
    }
  }
```

**Comment by hperrin** [comment]
This has been fixed. Btw, PNotify 4 won't support Bower, as the generated JS is not committed. If you can, you should switch to NPM. If not, someone can fork PNotify and commit the generated files.
