### ISSUE TITLE
Pnotify with custom jQuery

### ISSUE THREAD

**Issue by pacmandv** [sciactive/pnotify#251]
Hello,

How to correctly override $ jQuery for the pnotify?
I faced with a problem, if on the site installed an old version of jQuery, pnotify doesn't work. Update jQuery I can't, only include a new version of jQuery, but in global scope it uses old. So I want to pass to the plugin correct version of jQuery, a new one. What the best way for this?

Thanks.

**Comment by avnenkovskyi1** [comment]
Hello Support team,

Could you answer on question above, we have the same issue

**Comment by hperrin** [comment]
The new version of PNotify, v4, which is currently in alpha, no longer requires jQuery at all. It also has a number of other bugfixes and improvements.
