### ISSUE TITLE
Removing notices from history.

### ISSUE THREAD

**Issue by RildoInformatica** [sciactive/pnotify#253]
I can´t seem to find a way to remove pnotify notices from its history. Is there?

I´ve tried PNotify.removeAll() but this only removes the notices from the screen. But since I am using pnotify history module, I need a way to remove all notices from history.

Thanks to all in advance!

**Comment by hperrin** [comment]
The only way to do this would be to manually remove them from the `PNotify.notices` array. It should be something like this:

```js
PNotify.notices.splice(PNotify.notices.indexOf(notice), 1);
```
