### ISSUE TITLE
animate_speed is not working?

### ISSUE THREAD

**Issue by kushaljain03** [sciactive/pnotify#254]
Notification is not gone within 500ms. Where I did wrong ?
new PNotify({
        title: false,
        text: errorText,
        type: errorType,
        styling: 'bootstrap3',
        animate_speed: 500
    });

**Comment by pribilinskiy** [comment]
I've noticed that a class `ui-pnotify-fade-500` is added, but there are no rule exists for such class.
Perhaps it's assumed that one will add the css rule (missing in documentation)

```
.ui-pnotify.ui-pnotify-fade-500 {
    transition: opacity .5s linear;
    opacity: 0;
}
.ui-pnotify.ui-pnotify-fade-500.ui-pnotify.ui-pnotify-move {
    transition: opacity .5s linear, left .5s ease, top .5s ease, right .5s ease, bottom .5s ease;
}
```

**Comment by hperrin** [comment]
This option was taken out when PNotify started using all CSS based animations, but I forgot to remove it from the documentation. That was my bad.

**Comment by hperrin** [comment]
@pribilinskiy That's a good solution. I can include that in the documentation. Thank you.

**Comment by hperrin** [comment]
Or, not the option itself, but the including a number of ms part was taken out. It now just supports "fast", "normal", and "slow" by default.
