### ISSUE TITLE
How can I use it using ajax? 

### ISSUE THREAD

**Issue by hassansaqib** [sciactive/pnotify#255]
Hi, I am uploading the images and I do not need to reload the page. How can I show the notification on success or failure of upload? Should I use ajax? And how would I use it? 

Further I am using dropzone to upload files...

**Comment by hperrin** [comment]
You can create a new notice when your ajax code succeeds or fails. You should have some sort of callback option with whatever library you're using. Those callbacks are where you would create notices.
