### ISSUE TITLE
Bug? Cannot use 'in' operator to search for 'close' in undefined

### ISSUE THREAD

**Issue by hozza** [sciactive/pnotify#256]
I get the following error on Firefox & Safari & Chromium - Linux Mint and macOS... 

pnotify.js:38 Uncaught TypeError: Cannot use 'in' operator to search for 'close' in undefined
afterClose  @   pnotify.js:38
runModules  @   pnotify.js:8
(anonymous function)    @   pnotify.js:19
(anonymous function)    @   pnotify.js:22

I have the desktop module and callbacks module bundled. Anyone have any ideas? :S

**Comment by hperrin** [comment]
Thanks for the report. I've found the cause. I'll put this in a bugfix release for the 3.2 line.

**Comment by hperrin** [comment]
Fixed in the v3.2 branch.
