### ISSUE TITLE
Can i just put notices to right side ,don't pos next to left although not in viewport?

### ISSUE THREAD

**Issue by nightost** [sciactive/pnotify#258]
sometimes i have so much notices.
it's terrible that all notices are in view.

**Comment by nightost** [comment]
I don't understand.

**Comment by hperrin** [comment]
Yes. this is a new feature in v4, which is not yet in alpha stage. You can leave out `dir2` on the stack to get this behavior.

**Comment by hperrin** [comment]
v4 will probably be in beta some time next month, btw.
