### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by icepoint0** [sciactive/pnotify#259]
when i use webpack and common JS ; require("pnotify");and load the page;

its occurred  an error;

Cannot read property 'body' of undefined;

i even not use the new PNotify  constructor , how to fix this problem??

**Comment by ali32b** [comment]
I have the same problem.

**Comment by twig** [comment]
You'll need to modify your webpack configuration.

There's a fix here: https://github.com/sciactive/pnotify/issues/212#issuecomment-177952188

**Comment by hperrin** [comment]
This should be fixed now. You can reopen if it isn't.
