### ISSUE TITLE
File to import not found or unreadable: pnotify.

### ISSUE THREAD

**Issue by Faisal-nfl** [sciactive/pnotify#260]
I have application.scss file
when I write `@import "pnotify"` than it gives error
`File to import not found or unreadable: pnotify.`

Whats wrong with that

**Comment by hperrin** [comment]
I'm not sure what your file structure is, but maybe it should be

```
@import "node_modules/pnotify/dist/pnotify.css"
```

or

```
@import "pnotify.css"
```
