### ISSUE TITLE
Title and Text swapping places!

### ISSUE THREAD

**Issue by ZENUAV** [sciactive/pnotify#277]
I have installed pnotify using NuGet and have included the js and ccs in my page, so it's all working.

However when I run the following, the Title and Text are swapped in their positions??

        new PNotify({
            title: 'Regular Notice',
            text: 'Check me out! I\'m a notice.',
            styling: "fontawesome",
            type: "success",
            icon: 'fa fa-bug'
        });

i.e. Text goes at top near icon and Title underneath??

Am I doing something wrong??

**Comment by codymullins** [comment]
@ZENUAV can you open a fiddle for this? Using your exact code, it appears correctly for me. 

![image](https://user-images.githubusercontent.com/1738479/28694752-576ef076-72f9-11e7-81c4-b1c8df7bf923.png)

**Comment by hperrin** [comment]
The code on Nuget is very outdated. I don't know how to make a Nuget package, so I can't update it.
