### ISSUE TITLE
Options ignored

### ISSUE THREAD

**Issue by sasoriza** [sciactive/pnotify#284]
I can't get some of the options to work and I am clueless as to why. This is my code and neither the nonblock nor the desktop option is working.

    <script type="text/javascript">
        $j(document).ready(function(){
            var stack_topRight = {"dir1": "down", "dir2": "right", "push": "top"};
            var opts = {
                insert_brs: false,
                animate_speed: "fast",
                stack: stack_topRight,
                buttons: {
                  closer_hover: false,
                  sticker: false
                },
                nonblock: {
                    nonblock: true,
                    nonblock_opacity: .8
                },
                desktop: {
                  desktop: true
                }
            };
            $j('ul.messages>li').each(function() {
              opts.type = $j(this).hasClass('error-msg') ? 'error' : 'success' ;
              opts.icon = opts.type == 'error' ? 'fa fa-exclamation-triangle' : 'fa fa-check-circle-o';
              opts.text = $j(this).text();
              new PNotify(opts);
            });
        });
    </script>

**Comment by djmattyg007** [comment]
Do you have the desktop and nonblock modules on the page? They're optional features shipped as part of extra javascript files.

**Comment by hperrin** [comment]
I'm assuming you got it working. Be sure to include all the modules' JS/CSS files that you're using.
