### ISSUE TITLE
Reduce space between multiple notifications

### ISSUE THREAD

**Issue by amirhosseinmanian** [sciactive/pnotify#286]
I need to show multiple pnotifies closer to each other. Is there a setting for that or something else?
![notifies](https://cloud.githubusercontent.com/assets/25858420/23090496/6e778304-f5b4-11e6-8a20-7b9ee8c84c1d.png)

**Comment by amirhosseinmanian** [comment]
Temporary solution:
`
.ui-pnotify-container {
	margin-top: -30px;
}
`

**Comment by hperrin** [comment]
You can do this through the spacing properties on a stack. Like this:

    var stack_small_spaces = {"dir1": "down", "dir2": "left", "spacing1": 5, "spacing2": 5};
    PNotify.prototype.options.stack = stack_small_spaces;

**Comment by filipbekic01** [comment]
More simple solution: `PNotify.prototype.options.stack.spacing1 = 15`
