### ISSUE TITLE
Unable to remove inital non-block PNotify notification after setup

### ISSUE THREAD

**Issue by neoyeowyang** [sciactive/pnotify#287]
After setup (including the required .css and .js), I am unable to figure out how to remove the initial PNotify notification.

Did some tweaks with body onload -> "PNotify.removeAll();" but doesn't seem like the legit manner and upon hovering over the spot of the initial PNotify, it comes back.

I've also tried re-downloading the .css and .js without checking the non-block in non minified and minified versions but the initial PNotify was still there.

Been looking high and low but doesn't seem like anyone having the same issue as me or perhaps its just me. Appreciate any help or pointers, thank you!

**Comment by Giussep07** [comment]
Hola, buenas noches,

Yo también tenía el mismo problema y lo acabo de solucionar, primero noté que cuando abría la consola de desarrollador de chrome aparecía un mensaje init_PNotify. Empecé a buscar de donde aparecía este mensaje y provenía de un archivo en mi caso llamado "custom.min.js", que iniciaba una función llamada init_PNotify y lo que hace es crear esa molesta notificación, entonces elimine la función y con eso logré eliminar la notificación.
Espero sea de tu ayuda
Saludos

English version (Google translate) :)
Hi, first sorry for my english.
I also had the same problem and I just solved it, first I noticed that when I opened the chrome developer console I was shown an init_PNotify message. I started looking for where this message appeared and came from a file in my case called "custom.min.js", which started a function called init_PNotify and what it does is create that annoying notification, then delete the function and with that I managed to eliminate the notification.
I hope it's your help.
regards

**Comment by vvarchild** [comment]
up for this.. I had the same issue. Not being productive because of solving this problem. I already did what is said by @Giussep07  but it did not work for me the notification still pop up as if it was not deleted I tried to pinpoint other possible file but Jesus Christ I can't find it. Please help. I'm using the "custom.min.js" too..

**Comment by hperrin** [comment]
How are you including the JS in your page? Is it the file from the downloader at sciactive.com?

**Comment by farshidrezaei** [comment]
i have same issue. please heeeelp

**Comment by farshidrezaei** [comment]
I craete a trick for it.

just add this :

```
<script>
   $(document).ready(function (){
           $('.ui-pnotify').remove();
   });
</script>
```

**Comment by kunleawotunbo** [comment]
I was able to remove the annoying Welcome notification by commenting out init_PNotify() in the custom.min.js

If you can't find the custom.min.js file, try and search for the content of the welcome notification in your directory. "Welcome. Try hovering over me. " there, you will see the init_PNotify() method. 

I hope it solves it

**Comment by hperrin** [comment]
This code shouldn't be in the release. It should only exist on the demo page. Are you including code from a downloaded bundle or from NPM?

**Comment by RezaGhanbari** [comment]
As @kunleawotunbo mentioned this is the part of code that creates this message.

`function init_PNotify() {

			if( typeof (PNotify) === 'undefined'){ return; }
			console.log('init_PNotify');

			new PNotify({
			  title: "PNotify",
			  type: "info",
			  text: "Welcome. Try hovering over me. You can click things behind me, because I'm non-blocking.",
			  nonblock: {
				  nonblock: true
			  },
			  addclass: 'dark',
			  styling: 'bootstrap3',
			  hide: false,
			  before_close: function(PNotify) {
				PNotify.update({
				  title: PNotify.options.title + " - Enjoy your Stay",
				  before_close: null
				});

				PNotify.queueRemove();

				return false;
			  }
			});

		};`
 In order to remove this initial message, you should delete init_PNotify() from custom.min.js

**Comment by farshidrezaei** [comment]
@RezaGhanbari 
hi.  but this section code dose not exist  in mycustom.min.js.  
i first search for that.  but after not finding it,  i used the solution that i mentioned above.

**Comment by thesxw** [comment]
i found a consensus solution.
public_html/layouts/resources/helper.js

after this: Vtiger_Helper_Js.showPnotify(params);
add: Vtiger_Helper_Js.hidePnotify();
lines at work: 170-171

**Comment by MuhammadAhmadMir** [comment]
You just need to see the last function of custom.js. There you will find a **_`$(document).ready()`_** function. Just remove **_`init_PNotify()`_** from it.

**Comment by hperrin** [comment]
It looks like what you guys were seeing was because index.html was listed in Bower before. It is not included anymore, so it should work if you update PNotify in Bower. v4 will not support Bower, btw, so to stay current, you'll have to either move away from Bower, or fork PNotify and commit the generated JS files.

**Comment by hperrin** [comment]
Either that or gremlins.

**Comment by rramalho** [comment]
webpack.mix...
was always copying the files on my code. it was erasing the modifications before combine

**Comment by derlypacheco** [comment]
tengo el mismo problema y no encuentro como removelo por consola uso el remove 
PNotify.removeAll();
y funciona pero lo dejo en el codigo y no lo remueve

**Comment by jordisalord** [comment]
> Hola, buenas noches,
> 
> Yo también tenía el mismo problema y lo acabo de solucionar, primero noté que cuando abría la consola de desarrollador de chrome aparecía un mensaje init_PNotify. Empecé a buscar de donde aparecía este mensaje y provenía de un archivo en mi caso llamado "custom.min.js", que iniciaba una función llamada init_PNotify y lo que hace es crear esa molesta notificación, entonces elimine la función y con eso logré eliminar la notificación.
> Espero sea de tu ayuda
> Saludos
> 
> English version (Google translate) :)
> Hi, first sorry for my english.
> I also had the same problem and I just solved it, first I noticed that when I opened the chrome developer console I was shown an init_PNotify message. I started looking for where this message appeared and came from a file in my case called "custom.min.js", which started a function called init_PNotify and what it does is create that annoying notification, then delete the function and with that I managed to eliminate the notification.
> I hope it's your help.
> regards

It may come from "gentelella" bootstrap theme, "bower_components/gentelella/build/js/custom.min.js".

Thanks!

**Comment by JuinEsp** [comment]
> Eu crio um truque para isso.
> 
> basta adicionar isso:
> 
> ```
> <script>
>    $(document).ready(function (){
>            $('.ui-pnotify').remove();
>    });
> </script>
> ```

Funcionou muito bem para mim.
