### ISSUE TITLE
Cut new release to NPM to support webpack

### ISSUE THREAD

**Issue by sman591** [sciactive/pnotify#290]
A very important webpack fix was merged in #268, however a new release hasn't been made.

The diff from version 3.0.0 to now: https://github.com/sciactive/pnotify/compare/3.0.0...master

A new release would be much appreciated!

([temporary solution](https://github.com/sciactive/pnotify/issues/212#issuecomment-284802907))

**Comment by thedotedge** [comment]
👍

**Comment by codymullins** [comment]
+1

**Comment by zahedul** [comment]
+1

**Comment by codymullins** [comment]
@hperrin do you need help with maintaining this repository?

**Comment by nglelinh** [comment]
+1

**Comment by hperrin** [comment]
@codymullins, If you're willing, absolutely. I maintain this on my free time, which is scarce today, as I'm working at LinkedIn and running a podcast.

**Comment by hperrin** [comment]
Although, soon I plan to refactor the entire library to get rid of jQuery as a dependency.

**Comment by sman591** [comment]
@hperrin Any way we could get a 3.0.1 release in the meantime before a rewrite? The changes between 3.0.0 and master are relatively small: https://github.com/sciactive/pnotify/compare/3.0.0...master

**Comment by hperrin** [comment]
Yes. I'll be working on PNotify all day tomorrow, so I'll make a new release then.

**Comment by codymullins** [comment]
@hperrin I'll start poking through the code and issues to familiarize. Let me know what I can do to help - can see if there's any significant issues reported, how extensively are you planning on refactoring?

**Comment by hperrin** [comment]
Cody, I won't be refactoring a whole lot, just implementing things that jQuery is used for right now. The functionality should remain the same. Can you send me a DM on Twitter "@sciactive" and we can coordinate?

Everyone else, a new 3.0.1 release is out. It includes a new build system that uses Node instead of Bash, and now creates source maps.

**Comment by codymullins** [comment]
@hperrin I can't DM you on Twitter it seems: https://support.twitter.com/articles/14606
