### ISSUE TITLE
Would be very cool if we could pass the position of the alert as a parameter.

### ISSUE THREAD

**Issue by guilherme-ramalho** [sciactive/pnotify#297]

**Comment by hperrin** [comment]
I'm not sure what you mean. If you want an alert just positioned somewhere, you can use the stack option and pass in an object literal. Doing that means it would be in its own stack, and you couldn't put any other notices in that stack.

**Comment by hperrin** [comment]
So, something like:
```js
new PNotify({
  text: "Notice",
  stack: {"dir1": "down", "dir2": "right", "firstpos1": myYPos, "firstpos2": myXPos}
});
```
