### ISSUE TITLE
Unable to see source when pnotify becomes focussed

### ISSUE THREAD

**Issue by Chinese1904** [sciactive/pnotify#298]
Hi there,

Currently on your demo site you are not able to view the source from the dropdown menu for multiple items if the pnotify gains the focus and you need to opt out of it first before being able to do whatever else.

Just letting you know. Thanks for the work!

**Comment by hperrin** [comment]
Thanks for the heads up. I'm planning to redo the source buttons, so that you can click them without having to first click the demo button.

**Comment by hperrin** [comment]
Fixed on develop (v4).
