### ISSUE TITLE
Modal notifications leave empty element in DOM

### ISSUE THREAD

**Issue by todduk** [sciactive/pnotify#301]
When you create a modal notification and then close it, either by confirming, cancelling or closing, there is an empty element left at the top of the \<body\>.
`<div style="display: none;" class="ui-pnotify-modal-overlay"></div>`

Unclear if it should be being reused or deleted, but the issue is also present on the documentation page.

When any type of notif is open and you mouseout all of the left over elements are updated in some way (possibly opacity, can't tell, sorry).

**Comment by hperrin** [comment]
Ideally, the element should be destroyed when all notices in the modal stack have been closed and recreated if they are opened again.
