### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by donnytian** [sciactive/pnotify#303]
Can we add a progress bar at the bottom of notification? I don't see such feature in the demo page.
Just like what toastr has, to indicate the remaining time till dismiss.

Thanks for your great work, really!!!

**Comment by robinsonsvn** [comment]
I would love to see this functionality too

**Comment by hperrin** [comment]
I'd definitely like to add this. It may not make it into v4, though. Right now I'm focusing on making sure all v3 features still work after the rewrite.

**Comment by hperrin** [comment]
Gonna add this soon.

**Comment by hperrin** [comment]
Just finished with https://github.com/sciactive/pnotify/commit/f93efc5872bc475ce5b0949955c799b4a1f21c71

**Comment by hperrin** [comment]
Sorry, I got distracted... for almost 3 years.

https://github.com/sciactive/pnotify#countdown-module
