### ISSUE TITLE
How to remove inital non-block PNotify WelCome notification ? 

### ISSUE THREAD

**Issue by farshidrezaei** [sciactive/pnotify#304]
----------------------------------------------
|   ! Pnotify                                    |
|   Welcome. Try hovering over me.  |
|   You can click things behind me,   |
|   because I'm non-blocking.           |
----------------------------------------------

How Disable That?

**Comment by farshidrezaei** [comment]
i craete a trick for it. 

just add this : 

`
<script>
   $(document).ready(function ()
                     {

                        $('.ui-pnotify').remove();

                     });

</script>
`

**Comment by dizzy1021** [comment]
thanks dude
