### ISSUE TITLE
Recommended way of using with ES6 modules

### ISSUE THREAD

**Issue by OmgImAlexis** [sciactive/pnotify#305]
What's the recommended way to use this with ES6 module importing?

I've tried using `import PNotify from 'pnotify';` but that doesn't allow me to use the desktop module or override the prototype. I'm also using webpack if that changes anything.

**Comment by codymullins** [comment]
Can you try:

```
import * as PNotify from 'pnotify';
```

**Comment by codymullins** [comment]
Here's how I've done it:

```
import PNotify = require("pnotify");

require('pnotify/src/pnotify.buttons');
require('pnotify/src/pnotify.desktop');
```

**Comment by OmgImAlexis** [comment]
@codymullins I'd rather not use that method since it creates [side effects](https://en.wikipedia.org/wiki/Side_effect_%28computer_science%29). I was hoping there would be something I could import and then load into PNotify.

Something like this maybe.
```js
import PNotify from 'pnotify';

const notify = new PNotify({
    plugins: ['desktop']
});
```


Also I think you meant `import PNotify from "pnotify";` or `const PNotify = require("pnotify");`.

**Comment by codymullins** [comment]
@OmgImAlexis I use the import syntax above `import PNotify = require("pnotify");`, but that's using Typescript so it likely is what you've suggested for ES6. 

I agree about the side effects, unfortunately I haven't really found any other way. To be honest looking through the source it would probably take a little refactoring to improve upon this, but I could be wrong - the billion different ways to import things these days is something that still confuses me.

**Comment by joshnoe** [comment]
In the meantime, could the Readme please include "This library does not support ES6 module importing" at the top so those of us who need it don't waste our time with this?

**Comment by hperrin** [comment]
@codymullins Yeah, version 4.0 will be written in ES2017 and compiled to ES5 with Babel. It will also use Svelte instead of jQuery. (Svelte compiles to vanilla JS, so no dependencies.) Right now, I'm working out the best way to do that while maintaining as much backward compatibility as is reasonably possible.

@joshnoe I'm not interested in listing the technologies that aren't supported by my libraries. The readme already explains that PNotify uses AMD/RequireJS when they are detected.

**Comment by hperrin** [comment]
I've been working on version 4, and there is a working version now (though it's still a bit buggy). You can check out the `4.0-dev` branch to see it.

**Comment by hperrin** [comment]
Fixed in develop branch. (v4) There will be ES6 module builds in NPM with v4.
