### ISSUE TITLE
kepp desktop notification until user close it

### ISSUE THREAD

**Issue by dsmarques** [sciactive/pnotify#306]
Dear Sirs,
I'm using desktop pnotify in my application. This is the code:

PNotify.desktop.permission();
	new PNotify({
    
    text: 'Existe um pedido novo gravação! \n'+ m_grava,
	buttons:{
	closer: true
		},
    desktop: {
       icon: '../_lib/img/gip_logoaz2.png', 
		desktop: true,
		title: 'GRAVAÇÃO'
		
    },
	hide:false
	
});
I want to keep the notification visible until user close it. according to your documentation this will be possible with the parameter hide:false. But, I do not know why, the notification disappears after few seconds.
Any tip on how to solve this issue?

Regards,
David

**Comment by todduk** [comment]
I believe it depends on the implementation of desktop notifications by the browser developers. Firefox has a set limit of time that a notification can be displayed for, probably to prevent abuse. This is mentioned on the site unless I'm mistaken.

**Comment by hperrin** [comment]
Yeah, unfortunately, this is a browser limitation.
