### ISSUE TITLE
stack_bottomright is not defined? Terrible docs?

### ISSUE THREAD

**Issue by octoxan** [sciactive/pnotify#308]
When you go to the demo page and click "Stacks", the source code it gives you for every single solitary one of these is broken and unusable.

Why doesn't it tell you how to define stack_bottomright, or any of the others?

**Comment by hperrin** [comment]
The docs on GitHub explain how to use custom stacks.

**Comment by hperrin** [comment]
The documentation is clearer now, and there are no more classes you have to include either. (In develop branch, v4.)
