### ISSUE TITLE
Material CSS should not reference external URL

### ISSUE THREAD

**Issue by codymullins** [sciactive/pnotify#309]
When my internet went down, I noticed a suspicious failed URL call to `https://fonts.googleapis.com/css?family=Material+Icons` - which was odd, since our app is internal and we do not make external requests for resources like this. Any resource we have needs to be available locally.

I'm sure for the vast majority of people this doesn't matter, but for me (and likely many enterprise app developers) wouldn't want this. I'd like to request/suggest that this be an optional dependency that the developer installing the package should **intentionally** load this font in whatever format they need.

**Comment by anotherchrisatwork** [comment]
Agreed -- and it's worse for us, in that I'm developing an intranet application that has no connection to the internet, so the application hangs for a significant amount of time trying to load the font, *each time the page loads*.  Please fix!

**Comment by hperrin** [comment]
I don't think I can package the font with PNotify, but I can make it so the font's location is configurable.

**Comment by hperrin** [comment]
@codymullins Do you want to take this one?

**Comment by codymullins** [comment]
Yeah, I can grab it.

**Comment by codymullins** [comment]
I've attached the pull request #330

**Comment by hperrin** [comment]
Merged. :)
