### ISSUE TITLE
pnotify

### ISSUE THREAD

**Issue by AhmetBas** [sciactive/pnotify#319]
Hi,

We are using pnotify recently. So i was curious if it was possible to change the colors of the error pop-up? If yes which files should be changed in order to change the colors?

Kind regards,

Ahmet

**Comment by zhuber** [comment]
Hey @AhmetBas please check out the demo/documentation. There are some good examples of swapping the theme under the "Choose the styling" section and there is also a "Custom styles" item that you can view as well:
http://sciactive.com/pnotify/

**Comment by hperrin** [comment]
Using a styling object to apply custom classes is probably what you're looking for. The styling object looks like this:
```
        {
          container: "brighttheme",
          notice: "brighttheme-notice",
          notice_icon: "brighttheme-icon-notice",
          info: "brighttheme-info",
          info_icon: "brighttheme-icon-info",
          success: "brighttheme-success",
          success_icon: "brighttheme-icon-success",
          error: "brighttheme-error",
          error_icon: "brighttheme-icon-error"
        }
```
