### ISSUE TITLE
PNotify not defined or not a constructor

### ISSUE THREAD

**Issue by AdrianKuriata** [sciactive/pnotify#328]
Hi,  i updated to newest alpha version PNotify and tried use it with bootstrap4 and fontawesom4. Every time got error when import it with webpack like umd, es or iife. Just only when i imported ES module and use 

```
PNotify.default.defaults.styling = "bootstrap4";
		PNotify.default.defaults.icons = "fontawesome4";

		PNotify.default.alert({
```

Just start working, when i tried use `PNotify.defaults` and `PNotify.alert` i got error this is not defined. So if someone have a problem like me, just need tu use `PNotify.default.defaults` etc.

**Comment by hperrin** [comment]
If you're importing UMD, it will be the export called "default". You can use something like this:

```js
requirejs(['PNotify'], function(PNotify){
  PNotify = PNotify && PNotify.__esModule ? PNotify["default"] : PNotify;
  PNotify.notice({
    title: "Yay!",
    text: "It works!"
  });
});
```

**Comment by amoshydra** [comment]
Replacing 


```javascript
import PNotify from 'pnotify/dist/es';
```
Works for me on 4.0.0-alpha.2

**Comment by fnlopez10** [comment]
import PNotify from 'pnotify/dist/es/PNotify';
PNotify.alert('Notice me, senpai!');
