### ISSUE TITLE
how to use on codesandbox.io (for Svelte)

### ISSUE THREAD

**Issue by mspanish** [sciactive/pnotify#333]
Hey very cool you are already using Svelte - but do you know how I can import & use this in a codesandbox.io project that uses Svelte?  I tried adding it as a dependency and using 
`import { PNotify } from 'pnotify';`
but PNotify didn't work after that.

[My sandbox is here](https://codesandbox.io/s/1qzyn386ql)

Any ideas would be really great!

**Comment by hperrin** [comment]
Hi @mspanish. I think to import it in a module, you want to import the ES build, which is:

```js
import PNotify from 'pnotify/dist/es/PNotify';
```

To import it in a Svelte component, I think you'd use:

```js
import PNotify from 'pnotify/src/PNotify.html';
```

**Comment by hperrin** [comment]
I updated your sandbox [here](https://codesandbox.io/s/x7m1lnlv8o).

**Comment by mspanish** [comment]
awesome thank you so much - way better than the other thing I was looking at - much prettier!
