### ISSUE TITLE
addClass not working in pnotify using angular2

### ISSUE THREAD

**Issue by jainAdijain** [sciactive/pnotify#339]
I am using this in angular2 
following the steps below:

`npm instal pnotify --save`

**component.ts**
`import PNotify from 'pnotify/dist/es/PNotify';`

```
new PNotify ({
target: document.body;
data : {
title: 'Hey',
type: 'success',
addClass: 'notify-custom',
weight: '400px'
}
})
```

**component.scss**

```
.notify-custom {
background: grey;
border-12px;
}
```

In the Dev tools of css classes the class notify-custom is vsible but the properties of the class are neither visible nor applied.

**Comment by hperrin** [comment]
My guess is your selector is not specific enough. Did you check to see if your styles are being overridden?

**Comment by jainAdijain** [comment]
No the styles are not overridden, I have changed my selector many a time into different types, for reference I can show you the classes. 

You can see below my custom class name as notify-toast(changed from notify-custom to notify-toast that does not matter)

![image](https://user-images.githubusercontent.com/27722458/39460690-1e0007e4-4d23-11e8-94de-d2858a71133e.png)
