### ISSUE TITLE
h4 color conflict with bootstrap4

### ISSUE THREAD

**Issue by yepeekai** [sciactive/pnotify#341]
bootstrap 4 set the color for all headers h1, h2, h3, h4, h5, h6 to headings-color. By default, it is inherit, but we don't use the defaults... PNotify set color on the container div of the h4.  So h4 uses the color specified in bootstrap since the rule has precedence over pnotify.  Since PNotify tries to use a different color than the default one, I think it should also add the class on the h4 so that it takes precedence over the default h4 color.

**Comment by hperrin** [comment]
Good catch.

**Comment by hperrin** [comment]
Actually, it looks like even with the Bootstrap style, because it's set to `color: inherit`, it does get the color styling from the PNotify theme.
