### ISSUE TITLE
No alert function for PNotify?

### ISSUE THREAD

**Issue by chaochao** [sciactive/pnotify#347]
<img width="758" alt="screen shot 2018-09-28 at 12 03 27 pm" src="https://user-images.githubusercontent.com/3485580/46228318-90276d80-c316-11e8-83c0-de0696a68f9d.png">
Hi I just wondering, do you guys remove the alert static function from PNotify? 

I include the library in my file and I do get the PNotify object.
<script type="text/javascript" src="assets/js/plugins/notifications/pnotify.min.js"></script>

**Comment by hperrin** [comment]
It looks like you've included an older version of PNotify (pnotify.min.js is an older filename). Can you try with PNotify 4?
