### ISSUE TITLE
IE11 and Pnotify and Angular

### ISSUE THREAD

**Issue by Velocity540** [sciactive/pnotify#350]
Perhaps I am doing something wrong, but having an issue.
Using angular 6

in my component im importing like this (as stated in the docs)
     import PNotify from "pnotify/dist/es/PNotify";

All works well in chrome and edge. but in IE, getting this error
syntax error
on this line
      let onDocumentLoaded = () => {

Im sure its a quick config change, but not exactly sure what to do here

**Comment by hperrin** [comment]
There's a link in the README here: https://github.com/sciactive/pnotify#angular

To this issue, which includes a solution for IE support: https://github.com/sciactive/pnotify/issues/343#issuecomment-411881678

**Comment by Velocity540** [comment]
Yes.. Thank you.. I should have updated my ticket once I noticed that myself.. I must have glanced string over it.

**Comment by hperrin** [comment]
No worries. :)
