### ISSUE TITLE
How to get the values of multi-input Form

### ISSUE THREAD

**Issue by boulepick** [sciactive/pnotify#353]
Hi,
in version 3 i was able to get the input values of a form created through Pnotify. like below 

`          
          var notice = new Pnotify(param);

          notice
            .get()
            .find('form.custForm')
            .on('click', '[name=cancel]', () => {
              notice.remove();
            })
            .submit(function (e) {
              e.preventDefault();
              opt.cField = $.trim($(this).find('input[name=cField]').val());
              opt.cField1 = $.trim($(this).find('input[name=cField1]').val());
              opt.cSel = $.trim($('option:selected', $(this)).val());
              opt.cSelDesc = $('option:selected', $(this)).text();}`

however in version 4 this is not working.

how would i go to get the values of a multi-input form?

Thank you

**Comment by hperrin** [comment]
Instead of `notice.get()`, use `notice.refs.elem`.
