### ISSUE TITLE
automatic code formatting with Prettier

### ISSUE THREAD

**Issue by micahstubbs** [sciactive/pnotify#355]
automatic code formatting with Prettier

https://prettier.io/

will try out adding Prettier to the project and see if the results are nice.

**Comment by micahstubbs** [comment]
Prettier got more interesting for HTML-heavy projects like pnotify since it added support for HTML and js inside of HTML script tags a few months back in October 2018 https://github.com/prettier/prettier/pull/5259

**Comment by hperrin** [comment]
But, it doesn't play nicely with Svelte templates. :(

**Comment by micahstubbs** [comment]
hhhmmm there is https://github.com/UnwrittenFun/prettier-plugin-svelte

**Comment by hperrin** [comment]
Merged.
