### ISSUE TITLE
Directory "dist" is missing !!

### ISSUE THREAD

**Issue by alperyazgan** [sciactive/pnotify#361]
Literally it is missing from the package :-)

**Comment by Kunwark** [comment]
I am having the same issue.

**Comment by Kunwark** [comment]
@hperrin would you be able to fix this please?

**Comment by hperrin** [comment]
From the package or the repo?

**Comment by hperrin** [comment]
It is intentionally left out of the repo. It should be available in the NPM package.

**Comment by jitangupta** [comment]
I am using PNotify in a DotNet application and use Nuget as package manager.
How can I get the file to include in my application.
