### ISSUE TITLE
If notification has title only, the text is not vertically aligned

### ISSUE THREAD

**Issue by ppazos** [sciactive/pnotify#363]
I'm using notifications with title only, titles have a class that adds a margin-bottom, that makes the space below the text greater than the space above, making the text in the notification to appear not aligned vertically.

It would be better to add a margin-top to the contents of the notification when there are contents, instead of adding the margin bottom to the title.

Current:

![incorrect](https://user-images.githubusercontent.com/1278556/63135425-379ba600-bfa4-11e9-84b9-1381a6b791cb.png)

Expected:

![correct](https://user-images.githubusercontent.com/1278556/63135434-3e2a1d80-bfa4-11e9-8f12-3a4edf9a96f5.png)

**Comment by aasiph** [comment]
Add custom css in your stylesheet
```css
.customcss .ui-pnotify-title {
  margin-bottom: 0 !important;
}
```

Use addClass option to supply css class
```javascript
PNotify.info({
      title: "Button Clicked",
      addClass: 'customcss',
    });
```

**Comment by hperrin** [comment]
This is fixed in v5 (yet to be released as of this comment).
