### ISSUE TITLE
Svelte 3 Compatability

### ISSUE THREAD

**Issue by MintyMods** [sciactive/pnotify#364]
Hi, I am trying to integrate your awesome functionality into a Svelte 3 project I am working on and it complains about your usage of ref 

```
✗ client
E:\Development\MintySapper\node_modules\pnotify\src\PNotify.html
The ref directive is no longer supported — use `bind:this={elem}` instead
11: -->
12:
13: <div ref:elem
         ^
14:     class="
15:       ui-pnotify
✗ server
E:\Development\MintySapper\node_modules\pnotify\src\PNotify.html
The ref directive is no longer supported — use `bind:this={elem}` instead
11: -->
12:
13: <div ref:elem
         ^
14:     class="
15:       ui-pnotify
```

I assume this is because your current source is Svelte 2. Are there plans to upgrade your dependency to Svelte 3 and if so would there be any timescales for this?

Many thanks and Kind Regards
Minty

**Comment by hperrin** [comment]
Yeah, I do plan on migrating to Svelte 3, but that's currently in alpha. You should be able to use it, but I haven't had enough time to test it thoroughly.

**Comment by hperrin** [comment]
Feel free to submit any bugs you run into. :)

**Comment by MintyMods** [comment]
Fair enough my friend, and while I have your attention can I just say how much I like PNotify. 

I have made 'pop-up/pop-in' notifications etc. and have used many other solutions but PNotify seriously rocks when it comes to functionality and being an overall complete solution to notifications. 

Kudos to you and much respect.

**Comment by hperrin** [comment]
Thank you! That's awesome to hear! :D

**Comment by MintyMods** [comment]
I just found your 'Svelte-Material-UI' and couldn't be happier! Exactly what I was looking for! I have been learning Svelte/Sapper and using MaterializeCss UNTIL NOW where I start again on my UI. Thank you so much for your awesome contributions to my project :)
