### ISSUE TITLE
Using version 4 with Typescript, type definitions required

### ISSUE THREAD

**Issue by seagullmouse** [sciactive/pnotify#366]
For version 3 of PNotify I was able to use the type definitions from https://www.npmjs.com/package/@types/jquery.pnotify

I can't find type definitions that work with PNotify 4. 

Any idea when some might become available? Thanks

**Comment by hperrin** [comment]
Hi @seagullmouse. I'm working on them now. I should have them ready soon. I've been testing them on my work project, and they seem to be working well. Now I have to figure out how to get them into the packages.

**Comment by hperrin** [comment]
I'm starting to add these, but they will only be available in PNotify 5, so you should migrate soon.
