### ISSUE TITLE
Notification clarification

### ISSUE THREAD

**Issue by rkvignesh** [sciactive/pnotify#373]
I am using Pnotify.

When I am initially entering into a website i am being asked allow or block notifications.
![image](https://user-images.githubusercontent.com/53811429/70050563-43fc4b00-15f5-11ea-99dd-6eb168afa28f.png)

When I give block notifications, i am getting notification like this.
![image](https://user-images.githubusercontent.com/53811429/70050584-5a0a0b80-15f5-11ea-804b-1c047e825b59.png)

When I give block notifications, i am getting notification like this.
![image](https://user-images.githubusercontent.com/53811429/70050620-70b06280-15f5-11ea-97f3-f10230944050.png)

Why is this behaving like this?

Please clarify?

**Comment by hperrin** [comment]
The one you're seeing when you block notifications is the in browser notification. It's a DOM element on the page. The one you're seeing when you allow notifications is the web notification. It's an operating system level alert produced by the browser. Check out the docs for the desktop module for more info. If that's not the behavior you want, you can either deactivate or remove the desktop module.
