### ISSUE TITLE
PNotify with Svelte 3 not working

### ISSUE THREAD

**Issue by tonprince** [sciactive/pnotify#374]
I got an error when trying to build my web component with Svelte version 3:

`[!] (plugin svelte) ParseError: The ref directive is no longer supported — use `bind:this={elem}` instead
node_modules/pnotify/src/PNotify.html`

**Comment by hperrin** [comment]
The new version that’s in development will support Svelte 3. I’m hoping to get it out soon. At least in beta.

**Comment by ilrico** [comment]
in the meantime, with Svelte3 you can import like this way (ES6 version modified):
``import PNotify from 'pnotify/dist/es/PNotify.js' ``
and in index.html also remove the first directory node_modules such as:  
``<link href="pnotify/dist/PNotifyBrightTheme.css" rel="stylesheet" type="text/css" />``

@hperrin congrats for your work
