### ISSUE TITLE
Can confirm buttons text be changed?

### ISSUE THREAD

**Issue by ppazos** [sciactive/pnotify#377]
Can't find any documentation about that. I have a multilanguage app and need to change the default OK/Cancel texts on my confirms. Thanks!

**Comment by zandiarash** [comment]
Unfortunately Pnotify does not have a satisfiable documentation.
I have same Issue.
I've used **Pnotify>Confirm Module>Custom Buttons** to make buttons in different languages
But I could not find how to use **pnotify.confirm** with custom buttons.
```
 notice.on('pnotify.confirm', function() {
          alert('Ok, cool.');
        });
```

**Comment by hperrin** [comment]
They can be changed. You can set the buttons object to change their properties. You can spread the default's properties into your button objects and set the text after the spread properties. Or, to always change them, you can change the default text in the Confirm module's defaults.

**Comment by hperrin** [comment]
So, in PNotify 4, it would be:
```
PNotify.modules.Confirm.defaults.buttons[0].text = 'OK text';
PNotify.modules.Confirm.defaults.buttons[1].text = 'Cancel text';
```

**Comment by hperrin** [comment]
And in PNotify 5, it would be:
```
import { defaults } from '@pnotify/confirm';

defaults.buttons[0].text = 'OK text';
defaults.buttons[1].text = 'Cancel text';
```
