### ISSUE TITLE
Adding to frameset?

### ISSUE THREAD

**Issue by exetico** [sciactive/pnotify#382]
Hi

I'm trying to use pnotify on a page, where i only have a frameset. There's no option to add a body, so i need to find a work-around.

I can see that i'm able to define `target`, however, i'm unsure about how i should use it.

TL;DR:
Can i use pnotify, in a page where i only have a frameset, and frames - and _no body_?

**Comment by exetico** [comment]
I'm able to add content to the page with `$('<p>Testcontent</p>').insertBefore('frameset')` - but i'm not sure, how i can get PNotify to work.

**Comment by exetico** [comment]
I actually managed to add a body-dom to the page, with the following code:
```
	var customBody = document.createElement('body');
	customBody.id = "customBody";
	$(customBody).insertBefore('frameset');
```

But i would like to target a frame, if possible.

**Comment by hperrin** [comment]
You can change the context of a stack. As long as PNotify can add elements to that context, it should work.

To change the default stack context use

```
PNotify.defaultStack.context = someElementOrDocumentBody;
```

If your frame is on the same origin, I believe you should have access to its document body.

**Comment by hperrin** [comment]
You should change the stack context before creating any notices.

**Comment by exetico** [comment]
I'll do that, and see how it goes. Thanks!
