### ISSUE TITLE
Pnotify 5.0.0-alpha.3 added margin on text?

### ISSUE THREAD

**Issue by tcorley** [sciactive/pnotify#384]
With the same text on both versions, it seems that the latest adds margin to the text area so that less is shown.

Before: 
![Screen Shot 2020-02-26 at 10 23 19 AM](https://user-images.githubusercontent.com/3708319/75375254-9068c700-5882-11ea-8e2c-ddd1e54ff3f1.png)

After:
![Screen Shot 2020-02-26 at 10 23 42 AM](https://user-images.githubusercontent.com/3708319/75375269-96f73e80-5882-11ea-9578-511ccf9115f1.png)
![Screen Shot 2020-02-26 at 10 25 14 AM](https://user-images.githubusercontent.com/3708319/75375276-9a8ac580-5882-11ea-989a-4f18c7afe0ac.png)

**Comment by hperrin** [comment]
So, unfortunately this isn't possible with `maxTextHeight` set, since the floated buttons always create a margin on the text. You can get around this by added a title or removing the buttons.
