### ISSUE TITLE
Previous version (V4) documentation is missing

### ISSUE THREAD

**Issue by jitangupta** [sciactive/pnotify#387]
As the PNotify has been upgraded to V5, I am not able to see the V4.0.1 documentation.

**Comment by hperrin** [comment]
Hi @jitangupta 

It's available on the v4 branch:
https://github.com/sciactive/pnotify/tree/v4

I'll add links for previous versions to the README.

**Comment by hperrin** [comment]
Closed with https://github.com/sciactive/pnotify/commit/86564d3ea40941ffc1edc76688fa440fb226e760
