### ISSUE TITLE
Countdown module's colors make the direction of the countdown difficult to determine.

### ISSUE THREAD

**Issue by micahstubbs** [sciactive/pnotify#390]
The progress bar direction should match the direction of the text for the language specified in the user-agent.

So, for "en-us", the language is English, for which the direction of the text is left-to-right (LTR). So then, the direction of the linear progress at the bottom of the countdown notification should also be LTR.

https://stackoverflow.com/questions/673905/best-way-to-determine-users-locale-within-browser

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language

**Comment by micahstubbs** [comment]
We can observe the current RTL behavior of the Countdown notification type on the demos page https://sciactive.com/pnotify/#demos-modules

**Comment by hperrin** [comment]
It's counting down, so it's going from 100% to 0%. The progress bar is LTR, which you can see when it counts back up after putting your cursor over it.

I think the confusion here may be that the progress bar's color is the same as the background color of the notice, and its background color is the same as the border color of the notice.

I can make an option to swap the colors.
