### ISSUE TITLE
Does pnotify support HTML tag?

### ISSUE THREAD

**Issue by Netway-Warithar** [sciactive/pnotify#403]
PNotify options ```text``` Can't be allow HTML syntax.

![image](https://user-images.githubusercontent.com/52729676/99530224-9c2d8800-29d3-11eb-9721-21412962de2c.png)

Example https://codesandbox.io/s/pnotify-5-in-vanilla-es6-forked-mll2l?file=/src/index.js 

PNotify : v5.2.0

**Comment by irvv17** [comment]
Of course, it does it. You need to set  another param on the API like so:
```
function click() {
  pnotify.info({
    title: "Button Clicked",
    text: textArea,
    textTrusted: true
  });
}
```

With this, you are saying that the text will be trusted every time and will render the HTML in there.

References: 
[Documentation about this](https://github.com/sciactive/pnotify#options)

[I recreate an example for you](https://codesandbox.io/s/pnotify-5-in-vanilla-es6-html-support-1j24r?file=/src/index.js)

you don't need to create an Element btw...

Hope it helps you.!

**Comment by Netway-Warithar** [comment]
> Of course, it does it. You need to set another param on the API like so:
> 
> ```
> function click() {
>   pnotify.info({
>     title: "Button Clicked",
>     text: textArea,
>     textTrusted: true
>   });
> }
> ```
> 
> With this, you are saying that the text will be trusted every time and will render the HTML in there.
> 
> References:
> [Documentation about this](https://github.com/sciactive/pnotify#options)
> 
> [I recreate the example for you in codepen](https://codesandbox.io/s/pnotify-5-in-vanilla-es6-html-support-1j24r?file=/src/index.js)
> 
> you don't need to create an Element btw...
> 
> Hope it helps you.!

You helped me a lot, thank you very much.
