### ISSUE TITLE
FEATURE : click to close

### ISSUE THREAD

**Issue by rkyoku** [sciactive/pnotify#41]
Hi,

This would be great to be able to close the notification by clicking anywhere in the notification element (".ui-pnotify").

This feature is easy to add, and is especially useful for mobile devices with limited "click" area accuracy.

Pending this, is there a function to programmatically close the notification? This way, we would be able to add a global "click" hook on ".ui-pnotify" in order to close the notif.

Thank you for your interest in this suggestion,

**Comment by chfw** [comment]
Please note that since version 2.1, pnotify_remove() of a PNotify instance is renamed to remove()

**Comment by kafeltz** [comment]
i like @hperrin solution, it makes sense as it seems like a peculiar solution
