### ISSUE TITLE
Notifications center position

### ISSUE THREAD

**Issue by remithomas** [sciactive/pnotify#46]
It's possible to align the notification in the center (top) of the page ?
thanks

**Comment by pandur** [comment]
Hi, 
I'm using latest PNotify - is it possible that before_open is not called?
Above center example does not work....

**Comment by Nezam** [comment]
Yeah this trick does not work in the latest release.Confirmed from myend.

**Comment by hperrin** [comment]
This should be done with a stack.

**Comment by hperrin** [comment]
This should work for you:

```js
var stack_center = {"dir1": "down", "dir2": "right", "firstpos1": 25, "firstpos2": ($(window).width() / 2) - (Number(PNotify.prototype.options.width.replace(/\D/g, '')) / 2)};
$(window).resize(function(){
    stack_center.firstpos2 = ($(window).width() / 2) - (Number(PNotify.prototype.options.width.replace(/\D/g, '')) / 2);
});
new PNotify({text: "Hi there.", stack: stack_center});
```

**Comment by unformattmh** [comment]
Thanks hperrin! That stack should be included on the release.
