### ISSUE TITLE
close button not showing on "notifications"  with default installation and missing documentation

### ISSUE THREAD

**Issue by darkwish121** [sciactive/pnotify#96]
Hi,

I have an issue that close button is not showing on the notice. I have simply add files and  run the code without success.

Here is what I do

1: include all required files and jquery 1.10.3 file

![includefiles](https://f.cloud.github.com/assets/1590250/1993836/dab8e158-84e1-11e3-826c-054d8b26aa3a.png)

2: include function and call it
![pnotify](https://f.cloud.github.com/assets/1590250/1993851/21efe4c2-84e2-11e3-95e5-3ff898b2332a.png)

After calling, it shows "stack_bottomright is not defined" in firebug console.

Here documentation is missing as there is not mention that include following line.

```
var stack_bottomright = {"dir1": "up", "dir2": "left", "firstpos1": 25, "firstpos2": 25}; 
```

After add this line globally it works and show Notification in bottom right. But it have no close and pause button

![noclose](https://f.cloud.github.com/assets/1590250/1993928/6b35efe0-84e3-11e3-8596-fb896e318f7a.png)

3: But on the web page of http://pinesframework.org/pnotify/ it show fine notification with close and pause button please tell where things are going wrong

![alert](https://f.cloud.github.com/assets/1590250/1993943/abd2ddba-84e3-11e3-8536-ce641b34fcea.png)

**Comment by SahinCaner** [comment]
Could you solve this issue?

**Comment by hperrin** [comment]
@SahinCaner Can you show me how to reproduce this?

**Comment by hperrin** [comment]
@SahinCaner You might want to start a new bug, because this one appears to be unrelated to yours.

**Comment by faanahmed** [comment]
I had the same issue. Close button was not displaying.
The fix is to include 
pnotify.buttons.js and 
pnotify.buttons.css files.

**Comment by lukas-pierce** [comment]
`import 'pnotify/dist/pnotify.css';
import 'pnotify/dist/pnotify.brighttheme.css';
import 'pnotify/dist/pnotify.buttons.css';
import 'pnotify/dist/pnotify.buttons';
import PNotify from 'pnotify';

export function success() {
  new PNotify({
    title: title,
    text: text,
    type: 'success',
    hide: false,
    closer: false
  });
}`
